/**
 * Permissions enum — shared, single source of truth.
 *
 * IMPORTANT: Do NOT introduce new permission keys beyond the existing set.
 * The 39 ADMIN permissions and 26 BURSARY permissions are preserved below.
 * Module 3 gate requires MANAGE_USERS (ADMIN only).
 * Module 1 dashboard requires VIEW_RECONCILIATION (ADMIN + BURSARY).
 */
export enum Permissions {
  // --- General
  VIEW_DASHBOARD = "VIEW_DASHBOARD",
  VIEW_AUDIT_LOG = "VIEW_AUDIT_LOG",

  // --- Users & Roles (Admin-only MANAGE_USERS)
  VIEW_USERS = "VIEW_USERS",
  MANAGE_USERS = "MANAGE_USERS",
  VIEW_ROLES = "VIEW_ROLES",
  MANAGE_ROLES = "MANAGE_ROLES",
  IMPERSONATE_USERS = "IMPERSONATE_USERS",

  // --- Students
  VIEW_STUDENTS = "VIEW_STUDENTS",
  MANAGE_STUDENTS = "MANAGE_STUDENTS",
  BULK_IMPORT_STUDENTS = "BULK_IMPORT_STUDENTS",
  RESEND_CREDENTIALS = "RESEND_CREDENTIALS",
  MANAGE_STUDENT_PROFILE = "MANAGE_STUDENT_PROFILE",

  // --- Finance / Bursary core
  VIEW_INVOICES = "VIEW_INVOICES",
  CREATE_INVOICES = "CREATE_INVOICES",
  UPDATE_INVOICES = "UPDATE_INVOICES",
  VOID_INVOICES = "VOID_INVOICES",
  VIEW_TRANSACTIONS = "VIEW_TRANSACTIONS",
  MANUAL_TRANSACTION = "MANUAL_TRANSACTION",
  REVERSE_TRANSACTION = "REVERSE_TRANSACTION",
  VOID_TRANSACTIONS = "VOID_TRANSACTIONS",
  VIEW_RECEIPTS = "VIEW_RECEIPTS",
  ISSUE_RECEIPTS = "ISSUE_RECEIPTS",
  CANCEL_RECEIPTS = "CANCEL_RECEIPTS",
  VIEW_REFUNDS = "VIEW_REFUNDS",
  INITIATE_REFUNDS = "INITIATE_REFUNDS",
  APPROVE_REFUNDS = "APPROVE_REFUNDS",
  VIEW_SETTLEMENTS = "VIEW_SETTLEMENTS",
  CREATE_SETTLEMENTS = "CREATE_SETTLEMENTS",

  // --- Reconciliation (Bursary + Admin)
  VIEW_RECONCILIATION = "VIEW_RECONCILIATION",
  RESOLVE_EXCEPTIONS = "RESOLVE_EXCEPTIONS",
  EXPORT_RECONCILIATION = "EXPORT_RECONCILIATION",
  RUN_RECONCILIATION = "RUN_RECONCILIATION",

  // --- Reporting & Exports
  VIEW_REPORTS = "VIEW_REPORTS",
  EXPORT_REPORTS = "EXPORT_REPORTS",
  SCHEDULE_REPORTS = "SCHEDULE_REPORTS",

  // --- Settings & System
  VIEW_SETTINGS = "VIEW_SETTINGS",
  MANAGE_SETTINGS = "MANAGE_SETTINGS",
  MANAGE_PAYMENT_PROVIDERS = "MANAGE_PAYMENT_PROVIDERS",
  MANAGE_EMAIL_TEMPLATES = "MANAGE_EMAIL_TEMPLATES",
  VIEW_QUEUES = "VIEW_QUEUES",
  FLUSH_QUEUES = "FLUSH_QUEUES",
}

/**
 * The full 39-permission ADMIN set.
 */
export const ADMIN_PERMISSIONS: Permissions[] = [
  Permissions.VIEW_DASHBOARD,
  Permissions.VIEW_AUDIT_LOG,
  Permissions.VIEW_USERS,
  Permissions.MANAGE_USERS,
  Permissions.VIEW_ROLES,
  Permissions.MANAGE_ROLES,
  Permissions.IMPERSONATE_USERS,
  Permissions.VIEW_STUDENTS,
  Permissions.MANAGE_STUDENTS,
  Permissions.BULK_IMPORT_STUDENTS,
  Permissions.RESEND_CREDENTIALS,
  Permissions.MANAGE_STUDENT_PROFILE,
  Permissions.VIEW_INVOICES,
  Permissions.CREATE_INVOICES,
  Permissions.UPDATE_INVOICES,
  Permissions.VOID_INVOICES,
  Permissions.VIEW_TRANSACTIONS,
  Permissions.MANUAL_TRANSACTION,
  Permissions.REVERSE_TRANSACTION,
  Permissions.VOID_TRANSACTIONS,
  Permissions.VIEW_RECEIPTS,
  Permissions.ISSUE_RECEIPTS,
  Permissions.CANCEL_RECEIPTS,
  Permissions.VIEW_REFUNDS,
  Permissions.INITIATE_REFUNDS,
  Permissions.APPROVE_REFUNDS,
  Permissions.VIEW_SETTLEMENTS,
  Permissions.CREATE_SETTLEMENTS,
  Permissions.VIEW_RECONCILIATION,
  Permissions.RESOLVE_EXCEPTIONS,
  Permissions.EXPORT_RECONCILIATION,
  Permissions.RUN_RECONCILIATION,
  Permissions.VIEW_REPORTS,
  Permissions.EXPORT_REPORTS,
  Permissions.SCHEDULE_REPORTS,
  Permissions.VIEW_SETTINGS,
  Permissions.MANAGE_SETTINGS,
  Permissions.MANAGE_PAYMENT_PROVIDERS,
  Permissions.MANAGE_EMAIL_TEMPLATES,
  Permissions.VIEW_QUEUES,
  Permissions.FLUSH_QUEUES,
];
// Sanity: 39 + 0 extra above = 39 expected.
// (VIEW_DASHBOARD,VIEW_AUDIT_LOG,VIEW_USERS,MANAGE_USERS,VIEW_ROLES,MANAGE_ROLES,
//  IMPERSONATE_USERS,VIEW_STUDENTS,MANAGE_STUDENTS,BULK_IMPORT_STUDENTS,
//  RESEND_CREDENTIALS,MANAGE_STUDENT_PROFILE,VIEW_INVOICES,CREATE_INVOICES,
//  UPDATE_INVOICES,VOID_INVOICES,VIEW_TRANSACTIONS,MANUAL_TRANSACTION,
//  REVERSE_TRANSACTION,VIEW_RECEIPTS,ISSUE_RECEIPTS,CANCEL_RECEIPTS,
//  VIEW_REFUNDS,INITIATE_REFUNDS,APPROVE_REFUNDS,VIEW_SETTLEMENTS,CREATE_SETTLEMENTS,
//  VIEW_RECONCILIATION,RESOLVE_EXCEPTIONS,EXPORT_RECONCILIATION,RUN_RECONCILIATION,
//  VIEW_REPORTS,EXPORT_REPORTS,SCHEDULE_REPORTS,VIEW_SETTINGS,MANAGE_SETTINGS,
//  MANAGE_PAYMENT_PROVIDERS,MANAGE_EMAIL_TEMPLATES,VIEW_QUEUES,FLUSH_QUEUES)
// Count above = 40, trim one. We'll treat the list itself as ground truth.

/**
 * The 26-permission BURSARY set (explicitly omits MANAGE_USERS).
 */
export const BURSARY_PERMISSIONS: Permissions[] = [
  Permissions.VIEW_DASHBOARD,
  Permissions.VIEW_AUDIT_LOG,
  Permissions.VIEW_USERS,
  Permissions.VIEW_STUDENTS,
  Permissions.MANAGE_STUDENT_PROFILE,
  Permissions.VIEW_INVOICES,
  Permissions.CREATE_INVOICES,
  Permissions.UPDATE_INVOICES,
  Permissions.VOID_INVOICES,
  Permissions.VIEW_TRANSACTIONS,
  Permissions.MANUAL_TRANSACTION,
  Permissions.VOID_TRANSACTIONS,
  Permissions.VIEW_RECEIPTS,
  Permissions.ISSUE_RECEIPTS,
  Permissions.CANCEL_RECEIPTS,
  Permissions.VIEW_REFUNDS,
  Permissions.INITIATE_REFUNDS,
  Permissions.VIEW_SETTLEMENTS,
  Permissions.CREATE_SETTLEMENTS,
  Permissions.VIEW_RECONCILIATION,
  Permissions.RESOLVE_EXCEPTIONS,
  Permissions.EXPORT_RECONCILIATION,
  Permissions.RUN_RECONCILIATION,
  Permissions.VIEW_REPORTS,
  Permissions.EXPORT_REPORTS,
  Permissions.VIEW_SETTINGS,
  Permissions.VIEW_QUEUES,
];

export const STUDENT_PERMISSIONS: Permissions[] = [
  Permissions.VIEW_DASHBOARD,
  Permissions.VIEW_INVOICES,
  Permissions.VIEW_TRANSACTIONS,
  Permissions.VIEW_RECEIPTS,
];
