import express, { Request, Response } from 'express';
import { getDashboardStats, addStudent } from '../controllers/admin';
import { protect, restrictTo, requirePermission, bumpRolePermsVersion } from '../middlewares/auth';
import { z } from 'zod';
import jwt from 'jsonwebtoken';
import { validateBody, validateParams, validateQuery } from '../middlewares/validate';
import { CreateStudentSchema, StudentService } from '../services/student';
import {
  confirmStudentUpload,
  downloadErrorCsv,
  previewStudentUpload,
  stageStudentUpload,
} from '../controllers/bulkUpload';
import { Role, Prisma, AccountStatus, PaymentGateway, EmailType, EmailDeliveryStatus } from '@prisma/client';
import prisma from '../config/database';
import { RefundService } from '../services/refund';
import { adminListRefunds, adminApproveRefund, adminRejectRefund } from '../controllers/refunds';
import { catchAsync } from '../utils/catchAsync';
import { AdminSearchService } from '../services/search';
import { SystemSettingsService } from '../services/systemSettings';
import { AdminNotificationService } from '../services/adminNotification';
import { PERMISSION_DEFS } from '../services/permissionSeed';
import { buildBranding } from '../utils/branding';
import bcrypt from 'bcrypt';
import { reqIp, reqUa } from '../utils/http';
import { buildTwoSheetWorkbook } from '../utils/xlsxTemplate';
import { csvLineSafe, appendCsvIntegrityTrailer } from '../utils/security';
import rateLimit from 'express-rate-limit';
import {
  EmailTemplateService,
  EmailTemplateConfigPatchSchema,
} from '../services/emailTemplate';

const router = express.Router();

// ============ TEMPLATE ROUTES (mounted BEFORE protect — inline auth with HTML fallback) ============

const FRONTEND_URL_ADMIN = process.env.FRONTEND_URL || 'http://localhost:5173';

async function templateAuthCheckAdmin(req: Request, allowedRoles: string[]): Promise<{ ok: boolean; html?: string }> {
  let token: string | undefined;
  const authHeader = req.headers.authorization;
  if (authHeader && authHeader.startsWith('Bearer ')) token = authHeader.slice(7);
  if (!token && typeof (req.query as any).access_token === 'string') {
    token = (req.query as any).access_token as string;
  }
  let userId: number | null = null;
  let userRole: string | null = null;
  if (token) {
    try {
      const decoded = jwt.verify(token, process.env.JWT_SECRET as string) as any;
      if (typeof decoded?.id === 'number') {
        const u = await prisma.user.findUnique({ where: { id: decoded.id }, select: { id: true, role: true, accountStatus: true } });
        if (u && u.accountStatus === 'ACTIVE') { userId = u.id; userRole = u.role; }
      }
    } catch { /* ignore invalid token — fallback to html login link */ }
  }
  if (!userId || !userRole || !allowedRoles.includes(userRole)) {
    const redirect = encodeURIComponent(req.originalUrl);
    const html = `<html><head><title>Login Required</title></head><body style="font-family:system-ui,-apple-system,sans-serif;padding:40px;max-width:600px;margin:auto"><h2 style="color:#b91c1c">Login Required</h2><p>Your session expired. Please <a href="${FRONTEND_URL_ADMIN}/login?redirect=${redirect}" style="color:#2563eb;font-weight:600">click here to log in</a>.</p></body></html>`;
    return { ok: false, html };
  }
  (req as any).user = { id: userId, role: userRole };
  return { ok: true };
}

// --- Students templates (ADMIN ONLY) ---
router.get('/students/template.csv', catchAsync(async (req: Request, res: Response) => {
  const auth = await templateAuthCheckAdmin(req, ['ADMIN']);
  if (!auth.ok) {
    return res.status(401).type('text/html').send(auth.html!);
  }
  const UTF8_BOM = '\uFEFF';
  const header = [
    'firstName (required)',
    'lastName (required)',
    'matricNumber (required, unique)',
    'email (required, unique)',
    'phoneNumber (required)',
    'programmeCode (or programmeId) — BScCS / BScPH / etc',
    'programmeId (or programmeCode) — numeric id from database',
    'academicSession (required e.g. 2025/2026)',
    'academicSessionId (or academicSession)',
    'studentType (UNDERGRADUATE / POSTGRADUATE / DIPLOMA / SANDWICH)',
    'collegeCode (optional, auto-populated from programme)',
    'departmentCode (optional, auto-populated from programme)',
    'middleName (optional)',
    'password (optional, autogenerated if blank)',
    'jambNumber (optional)',
    'address (optional)',
  ];
  const sample = [
    'Chiamaka',
    'Okoro',
    '2025/SCI/0001',
    'chiamaka.okoro@university.edu.ng',
    '+2348012345678',
    'BScCS',
    '',
    '2025/2026',
    '',
    'UNDERGRADUATE',
    '',
    '',
    'Ngozi',
    'StuPass2025!',
    '456789012',
    '123 University Drive, Abuja',
  ];
  const content =
    UTF8_BOM +
    '# Required columns: firstName, lastName, matricNumber, email, phoneNumber\r\n' +
    '# Match programme/session either by NAME/CODE (preferred) or by numeric ID. Programme is REQUIRED to create a student. Academic session is REQUIRED. College + Department optional — auto-populated from programme.\r\n' +
    csvLineSafe(header) +
    csvLineSafe(sample);
  res.attachment('students-import-template.csv');
  res.setHeader('Content-Type', 'text/csv; charset=utf-8');
  res.setHeader('Cache-Control', 'public, max-age=60');
  res.status(200).send(content);
}));

router.get('/students/template.xlsx', catchAsync(async (req: Request, res: Response) => {
  const auth = await templateAuthCheckAdmin(req, ['ADMIN']);
  if (!auth.ok) {
    return res.status(401).type('text/html').send(auth.html!);
  }
  const templateHeader = [
    'firstName',
    'lastName',
    'matricNumber',
    'email',
    'phoneNumber',
    'programmeCode',
    'programmeId',
    'academicSession',
    'academicSessionId',
    'studentType',
    'collegeCode',
    'departmentCode',
    'middleName',
    'password',
    'jambNumber',
    'address',
  ];
  const templateSamples = [
    [
      'Chiamaka',
      'Okoro',
      '2025/SCI/0001',
      'chiamaka.okoro@university.edu.ng',
      '+2348012345678',
      'BScCS',
      '',
      '2025/2026',
      '',
      'UNDERGRADUATE',
      '',
      '',
      'Ngozi',
      'StuPass2025!',
      '456789012',
      '123 University Drive, Abuja',
    ],
  ];
  const colWidths = [14, 14, 18, 34, 18, 16, 14, 16, 18, 18, 14, 16, 14, 20, 16, 36];
  const instructionRows: string[][] = [
    ['#', 'Topic', 'Rule / Description', 'Example'],
    ['1', 'Required Fields', 'firstName, lastName, matricNumber, email, phoneNumber, programme, academicSession are all required', 'See Column Reference below'],
    ['2', 'Programme Matching', 'Provide EITHER programmeCode (preferred, e.g. BScCS) OR programmeId (numeric id from DB). Code takes precedence.', 'BScCS'],
    ['3', 'Session Matching', 'Provide EITHER academicSession label (e.g. 2025/2026) OR academicSessionId (numeric). Label takes precedence.', '2025/2026'],
    ['4', 'Auto-populated Fields', 'collegeCode and departmentCode are auto-populated from Programme — you may leave blank.', '(leave blank)'],
    ['5', 'Password', 'If blank, a strong random password is autogenerated. Min 8 chars if provided.', 'StuPass2025!'],
    ['6', 'studentType', 'UNDERGRADUATE / POSTGRADUATE / DIPLOMA / SANDWICH / PART_TIME / OTHER.', 'UNDERGRADUATE'],
  ];
  const columnNotes = [
    { header: 'firstName', required: true, note: 'Given name. Max 80 chars.' },
    { header: 'lastName', required: true, note: 'Family name. Max 80 chars.' },
    { header: 'matricNumber', required: true, note: 'Unique matriculation/student ID. Max 50 chars.' },
    { header: 'email', required: true, note: 'Unique valid email address. Max 254 chars.' },
    { header: 'phoneNumber', required: true, note: 'Active phone contact. Max 30 chars.' },
    { header: 'programmeCode', required: true, note: 'Code from Programmes page (e.g. BScCS). Prefer over programmeId.' },
    { header: 'programmeId', required: false, note: 'Alternative: numeric DB id of programme (ignored if programmeCode filled).' },
    { header: 'academicSession', required: true, note: 'Session label e.g. 2025/2026. Prefer over academicSessionId.' },
    { header: 'academicSessionId', required: false, note: 'Alternative: numeric DB id of session (ignored if academicSession filled).' },
    { header: 'studentType', required: false, note: 'UNDERGRADUATE / POSTGRADUATE / DIPLOMA / SANDWICH / OTHER.' },
    { header: 'collegeCode', required: false, note: 'Optional cross-check; auto-populated from programme if blank.' },
    { header: 'departmentCode', required: false, note: 'Optional cross-check; auto-populated from programme if blank.' },
    { header: 'middleName', required: false, note: 'Middle name(s). Max 80 chars.' },
    { header: 'password', required: false, note: 'Plaintext password (min 8 chars). Auto-generated if blank.' },
    { header: 'jambNumber', required: false, note: 'JAMB/UTME registration number if applicable.' },
    { header: 'address', required: false, note: 'Residential or contact address. Max 500 chars.' },
  ];
  const xlsx = await buildTwoSheetWorkbook({
    title: 'Student Directory — Bulk Import Template',
    instructionRows,
    templateHeader,
    templateSamples,
    colWidths,
    columnNotes,
  });
  res.attachment('students-import-template.xlsx');
  res.setHeader('Content-Type', xlsx.mimeType);
  res.setHeader('Cache-Control', 'public, max-age=60');
  res.status(200).send(xlsx.buffer);
}));

router.use(protect);

// Selective access: Non-email endpoints remain ADMIN-only.
// Email delivery log list/detail: ADMIN or BURSARY (PII is automatically masked per viewerRole).
// Email template edit + resend credentials: ADMIN-only.
router.use((req, res, next) => {
  const isEmailDeliveryLogRead =
    req.method === 'GET' &&
    (/^\/email-delivery-logs(\/|$)/.test(req.path));
  const isEmailTemplate = /^\/email-templates(\/|$)/.test(req.path);
  const isResendCredentials = /\/resend-credentials$/.test(req.path);
  const isAuditLogsRead =
    req.method === 'GET' && /^\/audit-logs(\/|$)/.test(req.path);
  const role = String((req as any).user?.role || '');

  if (isAuditLogsRead) {
    const requireRole = role === 'ADMIN'
      ? requirePermission('AUDIT_LOGS_VIEW_FULL')
      : role === 'BURSARY'
      ? requirePermission('AUDIT_LOGS_VIEW_LIMITED')
      : restrictTo('ADMIN');
    return requireRole(req, res, next);
  }
  if (isEmailDeliveryLogRead) {
    if (role === 'ADMIN' || role === 'BURSARY') return next();
    return res.status(403).json({ status: 'fail', message: 'Requires ADMIN or BURSARY role' });
  }
  if (isEmailTemplate || isResendCredentials) {
    if (role === 'ADMIN') return next();
    return res.status(403).json({ status: 'fail', message: 'Requires ADMIN role' });
  }
  // Default: all other routes remain strict ADMIN-only
  return restrictTo('ADMIN')(req, res, next);
});

const JSON_DB_NULL = Prisma.JsonNull;

type ReqLike = Partial<Pick<Request, 'headers' | 'ip'>> & { user?: Request['user'] };

async function writeAudit(
  req: ReqLike | undefined,
  data: {
    action: string;
    entityType: string;
    entityId: string | number;
    details?: any;
  }
) {
  const userId = (req as any)?.user?.id ?? null;
  const ipAddress = req ? reqIp(req as any) : null;
  const userAgent = req ? reqUa(req as any) : null;
  try {
    await prisma.auditLog.create({
      data: {
        action: data.action,
        entityType: data.entityType,
        entityId: String(data.entityId),
        userId,
        ipAddress: ipAddress ? String(ipAddress).slice(0, 64) : null,
        userAgent: userAgent ? String(userAgent).slice(0, 512) : null,
        details: data.details === undefined || data.details === null ? JSON_DB_NULL : (data.details as Prisma.InputJsonValue),
      },
    });
  } catch {
  }
}

router.get('/stats', getDashboardStats);
router.post('/students', requirePermission('CREATE_STUDENT'), validateBody(CreateStudentSchema), addStudent);

router.post('/students/upload', requirePermission('BULK_UPLOAD_STUDENTS'), stageStudentUpload);
router.get('/students/upload/:id', requirePermission('BULK_UPLOAD_STUDENTS'), previewStudentUpload);
router.get('/students/upload/:id/errors.csv', requirePermission('BULK_UPLOAD_STUDENTS'), downloadErrorCsv);
router.post('/students/upload/:id/confirm', requirePermission('BULK_UPLOAD_STUDENTS'), requirePermission('CREATE_STUDENT'), confirmStudentUpload);

// TODO: Add GET /admin/import-history route with requirePermission('VIEW_IMPORT_HISTORY') middleware
// when the import-history list endpoint is implemented.

router.get('/refunds', requirePermission('PROCESS_REFUND'), adminListRefunds);
const RefundIdParam = z.object({ id: z.coerce.number().int().positive() });
router.post('/refunds/:id/approve', requirePermission('PROCESS_REFUND'), validateParams(RefundIdParam), adminApproveRefund as any);
router.post('/refunds/:id/reject', requirePermission('PROCESS_REFUND'), validateParams(RefundIdParam), adminRejectRefund as any);

const AdminTxUpdatePatchBody = z.record(z.any());
router.patch('/transactions/:id', requirePermission('VERIFY_PAYMENT'),
  validateParams(RefundIdParam),
  validateBody(AdminTxUpdatePatchBody),
  catchAsync(async (req: any, res) => {
    const txId = Number(req.params.id);
    const tx = await prisma.transaction.findUnique({
      where: { id: txId },
      select: { id: true, status: true },
    });
    RefundService.assertTransactionMutable(tx, req.body ?? {});
    const allowed = new Set(['description', 'metadata']);
    const data: Record<string, any> = {};
    for (const k of Object.keys(req.body ?? {})) {
      if (allowed.has(k)) data[k] = (req.body as any)[k];
    }
    if (Object.keys(data).length === 0) {
      return res.status(200).json({ status: 'success', data: { id: txId, changed: false } });
    }
    const updated = await prisma.transaction.update({ where: { id: txId }, data });
    res.status(200).json({ status: 'success', data: updated });
  }),
);

const AuditLogsQuery = z.object({
  page: z.coerce.number().int().min(1).optional().default(1),
  limit: z.coerce.number().int().min(1).max(500).optional().default(50),
  action: z.string().optional(),
  entity: z.string().optional(),
  entityId: z.coerce.number().int().positive().optional(),
  userId: z.coerce.number().int().positive().optional(),
  dateFrom: z.coerce.date().optional(),
  dateTo: z.coerce.date().optional(),
});
router.get('/audit-logs', validateQuery(AuditLogsQuery), catchAsync(async (req: any, res) => {
  const { page, limit, action, entity, entityId, userId, dateFrom, dateTo } = req.query as any;
  const where: any = {};
  if (action) where.action = action;
  if (entity) where.entityType = entity;
  if (entityId) where.entityId = String(entityId);
  if (userId) where.userId = userId;
  if (dateFrom || dateTo) {
    where.createdAt = {} as any;
    if (dateFrom) where.createdAt.gte = dateFrom;
    if (dateTo) where.createdAt.lte = dateTo;
  }
  const skip = (page - 1) * limit;
  const [rows, count] = await Promise.all([
    prisma.auditLog.findMany({
      where,
      orderBy: { createdAt: 'desc' },
      skip,
      take: limit,
      include: { user: { select: { id: true, email: true, firstName: true, lastName: true, role: true } } },
    }),
    prisma.auditLog.count({ where }),
  ]);
  const totalPages = Math.max(1, Math.ceil(count / limit));
  res.status(200).json({
    status: 'success',
    data: {
      items: rows,
      pagination: { page, limit, total: count, totalPages, hasNext: page < totalPages, hasPrev: page > 1 },
      filters: {
        action: action || null,
        entity: entity || null,
        entityId: entityId || null,
        userId: userId || null,
        dateFrom: dateFrom || null,
        dateTo: dateTo || null,
      },
    },
  });
}));

router.get('/audit-logs/export.csv', validateQuery(AuditLogsQuery), catchAsync(async (req: any, res) => {
  const { action, entity, entityId, userId, dateFrom, dateTo, format } = req.query as any;
  const where: any = {};
  if (action) where.action = action;
  if (entity) where.entityType = entity;
  if (entityId) where.entityId = String(entityId);
  if (userId) where.userId = userId;
  if (dateFrom || dateTo) {
    where.createdAt = {} as any;
    if (dateFrom) where.createdAt.gte = dateFrom;
    if (dateTo) where.createdAt.lte = dateTo;
  }
  const rows = await prisma.auditLog.findMany({
    where,
    orderBy: { createdAt: 'desc' },
    take: 50000,
    include: { user: { select: { id: true, email: true, firstName: true, lastName: true, role: true } } },
  });
  const header = ['id', 'createdAt', 'action', 'entityType', 'entityId', 'userId', 'actorEmail', 'actorName', 'actorRole', 'ipAddress', 'userAgent', 'details'];
  let csv = '\uFEFF' + csvLineSafe(header);
  for (const r of rows) {
    const name = [r.user?.firstName, r.user?.lastName].filter(Boolean).join(' ');
    csv += csvLineSafe([r.id, r.createdAt?.toISOString() ?? '', r.action ?? '', r.entityType ?? '', r.entityId ?? '', r.userId ?? '', r.user?.email ?? '', name, r.user?.role ?? '', r.ipAddress ?? '', r.userAgent ?? '', r.details ?? '']);
  }
  const ts = (d: any) => (d ? new Date(d).toISOString().slice(0, 10).replace(/-/g, '') : 'all');
  const filename = `audit_logs_${ts(dateFrom)}_${ts(dateTo)}_${Date.now()}.csv`;
  res.setHeader('Content-Type', 'text/csv; charset=utf-8');
  res.setHeader('Content-Disposition', `attachment; filename=${filename}`);
  if (format === 'json') {
    res.setHeader('Content-Type', 'application/json; charset=utf-8');
    res.setHeader('Content-Disposition', `attachment; filename=audit_logs_${ts(dateFrom)}_${ts(dateTo)}.json`);
    return res.status(200).json({ status: 'success', data: { rows } });
  }
  const csvWithIntegrity = appendCsvIntegrityTrailer(csv);
  res.status(200).send(csvWithIntegrity);
}));

// ---------------------------------------------------------------------------
// Users CRUD (6 routes)
//   GET    /admin/users              list paginated/filtered
//   GET    /admin/users/:id          get one
//   POST   /admin/users              create (bcrypt hash)
//   PATCH  /admin/users/:id          update (email immutable)
//   POST   /admin/users/:id/deactivate  toggle accountStatus
//   POST   /admin/users/:id/reset-password
//   Permission: MANAGE_USERS
// ---------------------------------------------------------------------------

const USER_SELECT = {
  id: true,
  email: true,
  firstName: true,
  middleName: true,
  lastName: true,
  matricNumber: true,
  admissionNumber: true,
  jambNumber: true,
  college: true,
  department: true,
  program: true,
  level: true,
  academicSession: true,
  studentType: true,
  entryMode: true,
  admissionYear: true,
  graduationYear: true,
  phoneNumber: true,
  address: true,
  role: true,
  accountStatus: true,
  lastLoginAt: true,
  createdAt: true,
  updatedAt: true,
} as const;

const UserListQuery = z.object({
  page: z.coerce.number().int().min(1).optional().default(1),
  pageSize: z.coerce.number().int().min(1).max(500).optional().default(25),
  search: z.string().max(200).trim().optional(),
  role: z.enum([Role.ADMIN, Role.BURSARY, Role.STUDENT]).optional(),
  accountStatus: z.enum([AccountStatus.ACTIVE, AccountStatus.SUSPENDED, AccountStatus.GRADUATED, AccountStatus.WITHDRAWN]).optional(),
});

router.get(
  '/users',
  requirePermission('MANAGE_USERS'),
  validateQuery(UserListQuery),
  catchAsync(async (req: any, res) => {
    const { page, pageSize, search, role, accountStatus } = req.query as z.infer<typeof UserListQuery>;
    const skip = (page - 1) * pageSize;

    const where: Prisma.UserWhereInput = {};
    if (search) {
      where.OR = [
        { email: { contains: search } },
        { firstName: { contains: search } },
        { lastName: { contains: search } },
        { matricNumber: { contains: search } },
      ];
    }
    if (role) where.role = role;
    if (accountStatus) where.accountStatus = accountStatus;

    const [items, total] = await Promise.all([
      prisma.user.findMany({
        where,
        select: USER_SELECT as any,
        skip,
        take: pageSize,
        orderBy: { createdAt: 'desc' },
      }),
      prisma.user.count({ where }),
    ]);
    const pageCount = Math.max(1, Math.ceil(total / pageSize));
    res.status(200).json({
      status: 'success',
      data: { items, total, page, pageSize, pageCount },
    });
  }),
);

const UserIdParam = z.object({ id: z.coerce.number().int().positive() });

router.get(
  '/users/:id',
  requirePermission('MANAGE_USERS'),
  validateParams(UserIdParam),
  catchAsync(async (req: any, res) => {
    const { id } = req.params as z.infer<typeof UserIdParam>;
    const user = await prisma.user.findUnique({
      where: { id },
      select: USER_SELECT as any,
    });
    if (!user) {
      return res.status(404).json({ status: 'fail', message: 'User not found' });
    }
    res.status(200).json({ status: 'success', data: user });
  }),
);

const CreateUserSchema = z
  .object({
    email: z.string().email().max(254),
    password: z.string().min(8).max(128),
    firstName: z.string().min(1).max(80),
    middleName: z.string().max(80).optional().nullable(),
    lastName: z.string().min(1).max(80),
    matricNumber: z.string().trim().regex(/^\d{4}\/[A-Z]{3}\/\d{4}$/, "Matric number must match YYYY/AAA/NNNN (e.g. 2023/CSC/0012).").optional().nullable(),
    role: z.enum([Role.ADMIN, Role.BURSARY, Role.STUDENT]).default(Role.STUDENT),
    accountStatus: z.enum([AccountStatus.ACTIVE, AccountStatus.SUSPENDED]).default(AccountStatus.ACTIVE),
    phoneNumber: z.string().max(30).optional().nullable(),
  })
  .strict();

router.post(
  '/users',
  requirePermission('MANAGE_USERS'),
  validateBody(CreateUserSchema),
  catchAsync(async (req: any, res) => {
    const body = req.body as z.infer<typeof CreateUserSchema>;
    const existing = await prisma.user.findUnique({ where: { email: body.email } });
    if (existing) {
      return res.status(400).json({ status: 'fail', message: 'A user with this email already exists' });
    }
    const hashedPassword = await bcrypt.hash(body.password, 12);
    const data: Prisma.UserCreateInput = {
      email: body.email,
      password: hashedPassword,
      firstName: body.firstName,
      middleName: body.middleName ?? undefined,
      lastName: body.lastName,
      matricNumber: body.matricNumber ?? undefined,
      role: body.role,
      accountStatus: body.accountStatus,
      phoneNumber: body.phoneNumber ?? undefined,
    };
    const created: any = await prisma.user.create({
      data,
      select: USER_SELECT as any,
    });
    await writeAudit(req, {
      action: 'CREATE_USER',
      entityType: 'USER',
      entityId: created.id as number,
      details: { email: created.email, role: created.role },
    });
    res.status(201).json({ status: 'success', data: created });
  }),
);

const UpdateUserSchema = z
  .object({
    firstName: z.string().min(1).max(80).optional(),
    middleName: z.string().max(80).optional().nullable(),
    lastName: z.string().min(1).max(80).optional(),
    matricNumber: z.string().trim().regex(/^\d{4}\/[A-Z]{3}\/\d{4}$/, "Matric number must match YYYY/AAA/NNNN (e.g. 2023/CSC/0012).").optional().nullable(),
    role: z.enum([Role.ADMIN, Role.BURSARY, Role.STUDENT]).optional(),
    accountStatus: z.enum([AccountStatus.ACTIVE, AccountStatus.SUSPENDED, AccountStatus.GRADUATED, AccountStatus.WITHDRAWN]).optional(),
    phoneNumber: z.string().max(30).optional().nullable(),
  })
  .strict();

router.patch(
  '/users/:id',
  requirePermission('MANAGE_USERS'),
  validateParams(UserIdParam),
  validateBody(UpdateUserSchema),
  catchAsync(async (req: any, res) => {
    const { id } = req.params as z.infer<typeof UserIdParam>;
    const body = req.body as z.infer<typeof UpdateUserSchema>;
    const existing = await prisma.user.findUnique({ where: { id } });
    if (!existing) {
      return res.status(404).json({ status: 'fail', message: 'User not found' });
    }
    const updateData: Prisma.UserUpdateInput = {};
    if (body.firstName !== undefined) updateData.firstName = body.firstName;
    if (body.middleName !== undefined) updateData.middleName = body.middleName ?? undefined;
    if (body.lastName !== undefined) updateData.lastName = body.lastName;
    if (body.matricNumber !== undefined) updateData.matricNumber = body.matricNumber ?? undefined;
    if (body.role !== undefined) updateData.role = body.role;
    if (body.accountStatus !== undefined) updateData.accountStatus = body.accountStatus;
    if (body.phoneNumber !== undefined) updateData.phoneNumber = body.phoneNumber ?? undefined;

    if (Object.keys(updateData).length === 0) {
      const user = await prisma.user.findUnique({ where: { id }, select: USER_SELECT as any });
      return res.status(200).json({ status: 'success', data: user });
    }

    const updated = await prisma.user.update({
      where: { id },
      data: updateData,
      select: USER_SELECT as any,
    });
    const changedFields = Object.keys(updateData);
    await writeAudit(req, {
      action: 'UPDATE_USER',
      entityType: 'USER',
      entityId: id,
      details: { changedFields },
    });
    res.status(200).json({ status: 'success', data: updated });
  }),
);

router.post(
  '/users/:id/deactivate',
  requirePermission('MANAGE_USERS'),
  validateParams(UserIdParam),
  catchAsync(async (req: any, res) => {
    const { id } = req.params as z.infer<typeof UserIdParam>;
    const existing = await prisma.user.findUnique({ where: { id }, select: { id: true, accountStatus: true } });
    if (!existing) {
      return res.status(404).json({ status: 'fail', message: 'User not found' });
    }
    const newStatus = existing.accountStatus === AccountStatus.ACTIVE ? AccountStatus.SUSPENDED : AccountStatus.ACTIVE;
    const updated = await prisma.user.update({
      where: { id },
      data: { accountStatus: newStatus },
      select: USER_SELECT as any,
    });
    await writeAudit(req, {
      action: 'ACCOUNT_STATUS_CHANGE',
      entityType: 'USER',
      entityId: id,
      details: { oldStatus: existing.accountStatus, newStatus },
    });
    res.status(200).json({ status: 'success', data: updated });
  }),
);

const ResetPasswordSchema = z
  .object({
    newPassword: z.string().min(8).max(128),
  })
  .strict();

router.post(
  '/users/:id/reset-password',
  requirePermission('MANAGE_USERS'),
  validateParams(UserIdParam),
  validateBody(ResetPasswordSchema),
  catchAsync(async (req: any, res) => {
    const { id } = req.params as z.infer<typeof UserIdParam>;
    const { newPassword } = req.body as z.infer<typeof ResetPasswordSchema>;
    const existing = await prisma.user.findUnique({ where: { id } });
    if (!existing) {
      return res.status(404).json({ status: 'fail', message: 'User not found' });
    }
    const hashedPassword = await bcrypt.hash(newPassword, 12);
    await prisma.user.update({
      where: { id },
      data: { password: hashedPassword },
    });
    await writeAudit(req, {
      action: 'PASSWORD_RESET',
      entityType: 'USER',
      entityId: id,
      details: { email: existing.email },
    });
    res.status(200).json({ status: 'success', data: { message: 'Password reset successful' } });
  }),
);

// ---------------------------------------------------------------------------
// Roles CRUD (4 routes, STUDENT hidden)
//   POST   /admin/roles              atomically REPLACE role permissions
//   PATCH  /admin/roles/:role        atomically REPLACE role permissions
//   Permission: MANAGE_ROLES
// ---------------------------------------------------------------------------

const ROLE_META: Record<string, { name: string; description: string }> = {
  [Role.ADMIN]: { name: 'Administrator', description: 'Full system access with all permissions' },
  [Role.BURSARY]: { name: 'Bursary', description: 'Financial operations, payments and receipts' },
};

const RoleNameParam = z.object({ role: z.enum([Role.ADMIN, Role.BURSARY]) });

type RolePermRow = { permission: { key: string; name: string; category: string | null; description?: string | null } };

function buildRoleOut(role: string, permsRows: RolePermRow[]) {
  const meta = ROLE_META[role] ?? { name: role, description: '' };
  return {
    role,
    name: meta.name,
    description: meta.description,
    permissions: permsRows.map((rp) => ({
      ...rp.permission,
      category: rp.permission.category ?? 'Admin',
    })),
    permissionsCount: permsRows.length,
  };
}

async function loadRolePermissionKeys(role: string): Promise<string[]> {
  const rows = await prisma.rolePermission.findMany({
    where: { role: role as Role },
    select: { permission: { select: { key: true } } },
  });
  return rows.map((r) => r.permission.key);
}

async function replaceRolePermissions(
  req: ReqLike | undefined,
  role: string,
  permissionKeys: string[],
  auditAction: 'CREATE_ROLE' | 'UPDATE_ROLE'
) {
  const asRole = role as Role;
  const [perms, oldKeys] = await Promise.all([
    prisma.permission.findMany({
      where: { key: { in: permissionKeys } },
      select: { id: true, key: true },
    }),
    loadRolePermissionKeys(role),
  ]);
  const foundKeys = new Set(perms.map((p) => p.key));
  const missing = permissionKeys.filter((k) => !foundKeys.has(k));
  if (missing.length > 0) {
    return { ok: false as const, status: 400, error: `Unknown permission keys: ${missing.join(', ')}` };
  }
  const newSet = new Set(perms.map((p) => p.key));
  const oldSet = new Set(oldKeys);
  const addedKeys = perms.filter((p) => !oldSet.has(p.key)).map((p) => p.key).sort();
  const removedKeys = oldKeys.filter((k) => !newSet.has(k)).sort();

  const finalRows: RolePermRow[] = await prisma.$transaction(async (tx) => {
    await tx.rolePermission.deleteMany({ where: { role: asRole } });
    if (perms.length > 0) {
      await tx.rolePermission.createMany({
        data: perms.map((p) => ({ role: asRole, permissionId: p.id })),
        skipDuplicates: true,
      });
    }
    return tx.rolePermission.findMany({
      where: { role: asRole },
      include: { permission: { select: { key: true, name: true, category: true, description: true } } },
    });
  });

  const hasDiff = addedKeys.length > 0 || removedKeys.length > 0;
  let summary = 'No changes';
  if (hasDiff) {
    const parts: string[] = [];
    if (addedKeys.length) parts.push(`Added [${addedKeys.join(', ')}]`);
    if (removedKeys.length) parts.push(`Removed [${removedKeys.join(', ')}]`);
    summary = parts.join('; ');
  }
  if (hasDiff) {
    bumpRolePermsVersion();
    await writeAudit(req, {
      action: auditAction,
      entityType: 'ROLE',
      entityId: role,
      details: {
        permissionKeys: finalRows.map((r) => r.permission.key),
        addedKeys,
        removedKeys,
        summary,
      },
    });
  }

  return {
    ok: true as const,
    status: auditAction === 'CREATE_ROLE' ? 201 : 200,
    addedKeys,
    removedKeys,
    data: buildRoleOut(role, finalRows),
  };
}

router.get(
  '/roles',
  requirePermission('MANAGE_ROLES'),
  catchAsync(async (_req: any, res) => {
    const visibleRoles = [Role.ADMIN, Role.BURSARY];
    const items = await Promise.all(
      visibleRoles.map(async (r) => {
        const perms: RolePermRow[] = await prisma.rolePermission.findMany({
          where: { role: r },
          include: { permission: { select: { key: true, name: true, category: true, description: true } } },
        });
        return buildRoleOut(r, perms);
      })
    );
    res.status(200).json({ status: 'success', data: { items } });
  }),
);

router.get(
  '/roles/:role',
  requirePermission('MANAGE_ROLES'),
  validateParams(RoleNameParam),
  catchAsync(async (req: any, res) => {
    const { role } = req.params as z.infer<typeof RoleNameParam>;
    const perms: RolePermRow[] = await prisma.rolePermission.findMany({
      where: { role },
      include: { permission: { select: { key: true, name: true, category: true, description: true } } },
    });
    res.status(200).json({ status: 'success', data: buildRoleOut(role, perms) });
  }),
);

const CreateRoleSchema = z
  .object({
    role: z.enum([Role.ADMIN, Role.BURSARY]),
    permissionKeys: z.array(z.string().min(1).max(64)).min(1),
  })
  .strict();

router.post(
  '/roles',
  requirePermission('MANAGE_ROLES'),
  validateBody(CreateRoleSchema),
  catchAsync(async (req: any, res) => {
    const { role, permissionKeys } = req.body as z.infer<typeof CreateRoleSchema>;
    const result = await replaceRolePermissions(req, role, permissionKeys, 'CREATE_ROLE');
    if (!result.ok) {
      return res.status(result.status).json({ status: 'fail', message: result.error });
    }
    res.status(result.status).json({
      status: 'success',
      diff: { added: result.addedKeys, removed: result.removedKeys },
      data: result.data,
    });
  }),
);

const UpdateRoleSchema = z
  .object({
    permissionKeys: z.array(z.string().min(1).max(64)).min(1),
  })
  .strict();

router.patch(
  '/roles/:role',
  requirePermission('MANAGE_ROLES'),
  validateParams(RoleNameParam),
  validateBody(UpdateRoleSchema),
  catchAsync(async (req: any, res) => {
    const { role } = req.params as z.infer<typeof RoleNameParam>;
    const { permissionKeys } = req.body as z.infer<typeof UpdateRoleSchema>;
    const result = await replaceRolePermissions(req, role, permissionKeys, 'UPDATE_ROLE');
    if (!result.ok) {
      return res.status(result.status).json({ status: 'fail', message: result.error });
    }
    res.status(result.status).json({
      status: 'success',
      diff: { added: result.addedKeys, removed: result.removedKeys },
      data: result.data,
    });
  }),
);

// ---------------------------------------------------------------------------
// GET /admin/permissions  (15-entries + roles_assigned from PERMISSION_DEFS)
//   Permission: MANAGE_ROLES
// ---------------------------------------------------------------------------

router.get(
  '/permissions',
  requirePermission('MANAGE_ROLES'),
  catchAsync(async (_req: any, res) => {
    const allRolePerms = await prisma.rolePermission.findMany({
      include: { permission: { select: { key: true } } },
    });
    const byPermKey = new Map<string, string[]>();
    for (const rp of allRolePerms) {
      const k = rp.permission.key;
      if (!byPermKey.has(k)) byPermKey.set(k, []);
      byPermKey.get(k)!.push(rp.role);
    }
    const items = PERMISSION_DEFS.map((def) => ({
      key: def.key,
      name: def.name,
      category: def.category,
      description: def.description ?? null,
      roles_assigned: byPermKey.get(def.key) ?? [],
    }));
    res.status(200).json({ status: 'success', data: { items } });
  }),
);

// ---------------------------------------------------------------------------
// E1: Composite Global Search — GET /admin/search?q=
// ---------------------------------------------------------------------------

const AdminSearchQuery = z.object({
  q: z.string().min(1).max(200),
  limit: z.coerce.number().int().min(1).max(100).optional().default(20),
});
router.get(
  '/search',
  validateQuery(AdminSearchQuery),
  catchAsync(async (req: any, res) => {
    const { q, limit } = req.query as z.infer<typeof AdminSearchQuery>;
    const result = await AdminSearchService.composite(q, { limit });
    res.status(200).json({ status: 'success', data: result });
  }),
);

// ---------------------------------------------------------------------------
// System Settings CRUD singleton (id=1)
//   Permission: SYSTEM_SETTINGS
// ---------------------------------------------------------------------------

router.get(
  '/settings',
  requirePermission('SYSTEM_SETTINGS'),
  catchAsync(async (_req: any, res) => {
    const settings = await SystemSettingsService.get();
    res.status(200).json({ status: 'success', data: settings });
  }),
);

const SystemSettingsPatchSchema = z
  .object({
    universityName: z.string().min(1).max(200).optional(),
    universityLogoUrl: z.string().max(500).nullable().optional(),
    universityFaviconUrl: z.string().max(500).nullable().optional(),
    universityAddress: z.string().max(500).nullable().optional(),
    universityPhone: z.string().max(40).nullable().optional(),
    universityEmail: z.string().email().max(150).nullable().optional(),
    universityWebsite: z.string().max(200).nullable().optional(),
    paystackLiveEnabled: z.boolean().optional(),
    largePaymentThreshold: z.union([z.number().min(0), z.string().refine((v) => Number(v) >= 0).transform((v) => Number(v))]).optional(),
    importErrorThreshold: z.coerce.number().int().min(0).optional(),
    receiptFooterText: z.string().max(500).nullable().optional(),
    receiptBursarName: z.string().max(190).nullable().optional(),
    receiptBursarTitle: z.string().max(190).nullable().optional(),
    receiptBursarSignatureUrl: z.string().max(500).nullable().optional(),
    receiptPrefix: z.string().min(1).max(10).optional(),
    paymentRefPrefix: z.string().min(1).max(10).optional(),
  })
  .strict();

router.patch(
  '/settings',
  requirePermission('SYSTEM_SETTINGS'),
  validateBody(SystemSettingsPatchSchema),
  catchAsync(async (req: any, res) => {
    const rawPatch = req.body as z.infer<typeof SystemSettingsPatchSchema>;
    const patch: any = { ...rawPatch };
    if (patch.largePaymentThreshold !== undefined && patch.largePaymentThreshold !== null) {
      patch.largePaymentThreshold = new Prisma.Decimal(Number(patch.largePaymentThreshold));
    }
    const updated = await SystemSettingsService.update(patch, {
      updatedById: req.user?.id ?? undefined,
    });
    res.status(200).json({ status: 'success', data: updated });
  }),
);

// ---------------------------------------------------------------------------
// Payment Config (GET + PATCH toggle)
//   GET    /admin/payment-config
//   PATCH  /admin/payment-config
//   Permission: PAYSTACK_CONFIG
//   Audit: GATEWAY_TOGGLE
// ---------------------------------------------------------------------------

router.get(
  '/payment-config',
  requirePermission('PAYSTACK_CONFIG'),
  catchAsync(async (_req: any, res) => {
    const settings = await SystemSettingsService.get();
    const activeGateway = settings.activePaymentGateway ?? PaymentGateway.ALATPAY;
    const supportedGateways = [
      {
        key: PaymentGateway.PAYSTACK,
        label: 'Paystack',
        status: settings.activePaymentGateway === PaymentGateway.PAYSTACK ? 'ACTIVE' : 'INACTIVE',
      },
      {
        key: PaymentGateway.ALATPAY,
        label: 'ALAT Pay',
        status: settings.activePaymentGateway === PaymentGateway.ALATPAY ? 'ACTIVE' : 'INACTIVE',
      },
    ];
    res.status(200).json({
      status: 'success',
      data: { activeGateway, supportedGateways },
    });
  }),
);

const PaymentConfigPatchSchema = z
  .object({
    activeGateway: z.enum([PaymentGateway.PAYSTACK, PaymentGateway.ALATPAY]),
  })
  .strict();

router.patch(
  '/payment-config',
  requirePermission('PAYSTACK_CONFIG'),
  validateBody(PaymentConfigPatchSchema),
  catchAsync(async (req: any, res) => {
    const { activeGateway } = req.body as z.infer<typeof PaymentConfigPatchSchema>;
    const before = await SystemSettingsService.get();
    const updated = await SystemSettingsService.update(
      { activePaymentGateway: activeGateway } as any,
      { updatedById: req.user?.id ?? undefined },
    );
    await writeAudit(req, {
      action: 'GATEWAY_TOGGLE',
      entityType: 'PAYMENT_CONFIG',
      entityId: '1',
      details: {
        oldGateway: before.activePaymentGateway ?? null,
        newGateway: activeGateway,
      },
    });
    const supportedGateways = [
      {
        key: PaymentGateway.PAYSTACK,
        label: 'Paystack',
        status: updated.activePaymentGateway === PaymentGateway.PAYSTACK ? 'ACTIVE' : 'INACTIVE',
      },
      {
        key: PaymentGateway.ALATPAY,
        label: 'ALAT Pay',
        status: updated.activePaymentGateway === PaymentGateway.ALATPAY ? 'ACTIVE' : 'INACTIVE',
      },
    ];
    res.status(200).json({
      status: 'success',
      data: {
        activeGateway: updated.activePaymentGateway,
        supportedGateways,
      },
    });
  }),
);

// ---------------------------------------------------------------------------
// Admin Notifications
// ---------------------------------------------------------------------------

const NotifListQuery = z.object({
  read: z.enum(['unread', 'all']).optional().default('unread'),
  page: z.coerce.number().int().min(1).max(100).optional().default(1),
  limit: z.coerce.number().int().min(1).max(100).optional().default(25),
});
router.get(
  '/notifications',
  validateQuery(NotifListQuery),
  catchAsync(async (req: any, res) => {
    const { read, page, limit } = req.query as z.infer<typeof NotifListQuery>;
    const result = await AdminNotificationService.listNotifications({ read, page, limit });
    res.status(200).json({ status: 'success', data: result });
  }),
);

const NotifIdParam = z.object({ id: z.coerce.number().int().positive() });
router.post(
  '/notifications/:id/read',
  validateParams(NotifIdParam),
  catchAsync(async (req: any, res) => {
    const { id } = req.params as z.infer<typeof NotifIdParam>;
    const userId = Number(req.user?.id ?? 0);
    if (!userId || userId <= 0) {
      return res.status(401).json({ status: 'fail', message: 'Authentication required' });
    }
    const marked = await AdminNotificationService.markRead(id, userId);
    res.status(200).json({ status: 'success', data: marked });
  }),
);

// ---------------------------------------------------------------------------
// Admin: Payments list (transactions with student/invoice/fee/receipt includes)
// ---------------------------------------------------------------------------
const AdminPaymentListQuery = z.object({
  page: z.coerce.number().int().min(1).max(100).optional().default(1),
  pageSize: z.coerce.number().int().min(1).max(100).optional().default(25),
  sort: z.string().optional().default('createdAt'),
  order: z.enum(['asc', 'desc']).optional().default('desc'),
  q: z.string().trim().max(200).optional(),
  status: z.enum(['PENDING', 'SUCCESS', 'FAILED', 'REVERSED']).optional(),
  gateway: z.enum(['PAYSTACK', 'ALATPAY']).optional(),
  dateFrom: z.string().optional(),
  dateTo: z.string().optional(),
  studentId: z.coerce.number().int().positive().optional(),
  feeId: z.coerce.number().int().positive().optional(),
  invoiceId: z.coerce.number().int().positive().optional(),
});

router.get(
  '/payments',
  requirePermission('VIEW_PAYMENTS'),
  validateQuery(AdminPaymentListQuery),
  catchAsync(async (req: any, res) => {
    const q = req.query as z.infer<typeof AdminPaymentListQuery>;
    const page = q.page;
    const pageSize = q.pageSize;
    const skip = (page - 1) * pageSize;

    const where: any = {};
    if (q.status) where.status = q.status;
    if (q.gateway) where.gateway = q.gateway;
    if (q.studentId) where.userId = q.studentId;
    if (q.invoiceId) where.invoiceId = q.invoiceId;
    if (q.feeId) where.invoice = { feeId: q.feeId };
    if (q.dateFrom || q.dateTo) {
      where.createdAt = {};
      if (q.dateFrom) where.createdAt.gte = new Date(q.dateFrom);
      if (q.dateTo) where.createdAt.lte = new Date(q.dateTo + 'T23:59:59.999Z');
    }
    if (q.q) {
      where.OR = [
        { reference: { contains: q.q, mode: 'insensitive' } },
        { paystackReference: { contains: q.q, mode: 'insensitive' } },
        { user: { OR: [
          { firstName: { contains: q.q, mode: 'insensitive' } },
          { lastName: { contains: q.q, mode: 'insensitive' } },
          { email: { contains: q.q, mode: 'insensitive' } },
          { matricNumber: { contains: q.q, mode: 'insensitive' } },
        ]}},
        { invoice: { OR: [
          { invoiceNumber: { contains: q.q, mode: 'insensitive' } },
          { fee: { OR: [
            { name: { contains: q.q, mode: 'insensitive' } },
            { feeCode: { contains: q.q, mode: 'insensitive' } },
          ]}},
        ]}},
      ];
    }

    const orderBy: any = {};
    const allowedSorts: Record<string, string> = {
      createdAt: 'createdAt', amount: 'amount', status: 'status',
    };
    orderBy[allowedSorts[q.sort as string] || 'createdAt'] = q.order || 'desc';

    const [items, total] = await Promise.all([
      prisma.transaction.findMany({
        where,
        skip, take: pageSize,
        orderBy,
        include: {
          user: { select: { id: true, firstName: true, lastName: true, email: true, matricNumber: true } },
          invoice: { select: { id: true, invoiceNumber: true, fee: { select: { id: true, name: true, feeCode: true } } } },
          receipts: { take: 1, orderBy: { generatedAt: 'desc' }, select: { id: true, receiptNumber: true, verificationToken: true, isVoided: true } },
        },
      }),
      prisma.transaction.count({ where }),
    ]);

    res.status(200).json({
      status: 'success',
      data: {
        items,
        total,
        page,
        pageSize,
        totalPages: Math.ceil(total / pageSize),
      },
    });
  }),
);

// ---------------------------------------------------------------------------
// Admin: Receipts list
// ---------------------------------------------------------------------------
const AdminReceiptListQuery = z.object({
  page: z.coerce.number().int().min(1).max(100).optional().default(1),
  pageSize: z.coerce.number().int().min(1).max(100).optional().default(25),
  sort: z.string().optional().default('paidAt'),
  order: z.enum(['asc', 'desc']).optional().default('desc'),
  q: z.string().trim().max(200).optional(),
  isVoided: z.enum(['true', 'false']).optional(),
  dateFrom: z.string().optional(),
  dateTo: z.string().optional(),
  studentId: z.coerce.number().int().positive().optional(),
  feeId: z.coerce.number().int().positive().optional(),
});

router.get(
  '/receipts',
  requirePermission('VIEW_RECEIPTS'),
  validateQuery(AdminReceiptListQuery),
  catchAsync(async (req: any, res) => {
    const q = req.query as z.infer<typeof AdminReceiptListQuery>;
    const page = q.page;
    const pageSize = q.pageSize;
    const skip = (page - 1) * pageSize;

    const where: any = {};
    if (q.isVoided === 'true') where.isVoided = true;
    if (q.isVoided === 'false') where.isVoided = false;
    if (q.studentId) where.studentId = q.studentId;
    if (q.feeId) where.invoice = { feeId: q.feeId };
    if (q.dateFrom || q.dateTo) {
      where.paidAt = {};
      if (q.dateFrom) where.paidAt.gte = new Date(q.dateFrom);
      if (q.dateTo) where.paidAt.lte = new Date(q.dateTo + 'T23:59:59.999Z');
    }
    if (q.q) {
      where.OR = [
        { receiptNumber: { contains: q.q, mode: 'insensitive' } },
        { verificationToken: { contains: q.q, mode: 'insensitive' } },
        { student: { OR: [
          { firstName: { contains: q.q, mode: 'insensitive' } },
          { lastName: { contains: q.q, mode: 'insensitive' } },
          { email: { contains: q.q, mode: 'insensitive' } },
          { matricNumber: { contains: q.q, mode: 'insensitive' } },
        ]}},
        { invoice: { OR: [
          { invoiceNumber: { contains: q.q, mode: 'insensitive' } },
          { fee: { OR: [
            { name: { contains: q.q, mode: 'insensitive' } },
            { feeCode: { contains: q.q, mode: 'insensitive' } },
          ]}},
        ]}},
      ];
    }

    const orderBy: any = {};
    const allowedSorts: Record<string, string> = {
      paidAt: 'paidAt', paidAmount: 'paidAmount', receiptNumber: 'receiptNumber',
    };
    orderBy[allowedSorts[q.sort as string] || 'paidAt'] = q.order || 'desc';

    const [items, total] = await Promise.all([
      prisma.receipt.findMany({
        where,
        skip, take: pageSize,
        orderBy,
        include: {
          student: { select: { id: true, firstName: true, lastName: true, email: true, matricNumber: true } },
          invoice: { select: { id: true, invoiceNumber: true, fee: { select: { id: true, name: true, feeCode: true } } } },
          transaction: { select: { reference: true, paystackChannel: true, gateway: true, type: true, amount: true, status: true, createdAt: true } },
          voidedBy: { select: { id: true, firstName: true, lastName: true, email: true } },
        },
      }),
      prisma.receipt.count({ where }),
    ]);

    res.status(200).json({
      status: 'success',
      data: {
        items,
        total,
        page,
        pageSize,
        totalPages: Math.ceil(total / pageSize),
      },
    });
  }),
);

router.get(
  '/receipts/export.csv',
  requirePermission('VIEW_RECEIPTS'),
  validateQuery(AdminReceiptListQuery),
  catchAsync(async (req: any, res) => {
    const q = req.query as z.infer<typeof AdminReceiptListQuery>;
    const where: any = {};
    if (q.isVoided === 'true') where.isVoided = true;
    if (q.isVoided === 'false') where.isVoided = false;
    if (q.studentId) where.studentId = q.studentId;
    if (q.feeId) where.invoice = { feeId: q.feeId };
    if (q.dateFrom || q.dateTo) {
      where.paidAt = {};
      if (q.dateFrom) where.paidAt.gte = new Date(q.dateFrom);
      if (q.dateTo) where.paidAt.lte = new Date(q.dateTo + 'T23:59:59.999Z');
    }
    if (q.q) {
      where.OR = [
        { receiptNumber: { contains: q.q, mode: 'insensitive' } },
        { verificationToken: { contains: q.q, mode: 'insensitive' } },
        { student: { OR: [
          { firstName: { contains: q.q, mode: 'insensitive' } },
          { lastName: { contains: q.q, mode: 'insensitive' } },
          { email: { contains: q.q, mode: 'insensitive' } },
          { matricNumber: { contains: q.q, mode: 'insensitive' } },
        ]}},
        { invoice: { OR: [
          { invoiceNumber: { contains: q.q, mode: 'insensitive' } },
          { fee: { OR: [
            { name: { contains: q.q, mode: 'insensitive' } },
            { feeCode: { contains: q.q, mode: 'insensitive' } },
          ]}},
        ]}},
      ];
    }
    const rows = await prisma.receipt.findMany({
      where,
      take: 50000,
      orderBy: { paidAt: 'desc' },
      include: {
        student: { select: { id: true, firstName: true, lastName: true, email: true, matricNumber: true } },
        invoice: { select: { id: true, invoiceNumber: true, fee: { select: { id: true, name: true, feeCode: true } } } },
        transaction: { select: { reference: true, paystackChannel: true, gateway: true, type: true, amount: true, status: true, createdAt: true } },
      },
    });
    const header = ['receiptNumber', 'verificationToken', 'paidAt', 'paidAmount', 'studentName', 'studentEmail', 'matricNumber', 'invoiceNumber', 'feeName', 'feeCode', 'gateway', 'channel', 'txReference', 'status', 'voided'];
    let csv = '\uFEFF' + csvLineSafe(header);
    for (const r of rows) {
      const stu = r.student as any;
      const stuName = [stu?.firstName, stu?.lastName].filter(Boolean).join(' ');
      const inv = r.invoice as any;
      const tx = r.transaction as any;
      csv += csvLineSafe([
        r.receiptNumber, r.verificationToken, r.paidAt?.toISOString() ?? '', String(r.paidAmount ?? ''),
        stuName, stu?.email ?? '', stu?.matricNumber ?? '', inv?.invoiceNumber ?? '',
        inv?.fee?.name ?? '', inv?.fee?.feeCode ?? '', tx?.gateway ?? '', tx?.paystackChannel ?? '',
        tx?.reference ?? '', tx?.status ?? '', r.isVoided ? 'YES' : 'NO',
      ]);
    }
    const ts = (d: any) => (d ? new Date(String(d)).toISOString().slice(0, 10).replace(/-/g, '') : 'all');
    const filename = `admin_receipts_${ts(q.dateFrom)}_${ts(q.dateTo)}_${Date.now()}.csv`;
    res.setHeader('Content-Type', 'text/csv; charset=utf-8');
    res.setHeader('Content-Disposition', `attachment; filename=${filename}`);
    if (((q as any).format ?? 'csv') === 'json') {
      res.setHeader('Content-Type', 'application/json; charset=utf-8');
      res.setHeader('Content-Disposition', `attachment; filename=admin_receipts_${ts(q.dateFrom)}_${ts(q.dateTo)}.json`);
      return res.status(200).json({ status: 'success', data: { rows } });
    }
    const csvWithIntegrity = appendCsvIntegrityTrailer(csv);
    res.status(200).send(csvWithIntegrity);
  }),
);

// ---------------------------------------------------------------------------
// Admin: Download formal receipt PDF by id (bypass student-scope check)
// ---------------------------------------------------------------------------
const ReceiptIdParam = z.object({ id: z.coerce.number().int().positive() });
router.get(
  '/receipts/:id/download',
  requirePermission('GENERATE_RECEIPT'),
  validateParams(ReceiptIdParam),
  catchAsync(async (req: any, res: any, next: any) => {
    const { downloadFormalReceipt } = await import('../controllers/receipt');
    return downloadFormalReceipt(req, res, next);
  }),
);

// ---------------------------------------------------------------------------
// Admin: Verify receipt by verificationToken OR receiptNumber (inline panel)
// ---------------------------------------------------------------------------
const ReceiptVerifyParam = z.object({ tokenOrNumber: z.string().min(1).max(100).trim() });
router.get(
  '/receipts/verify/:tokenOrNumber',
  requirePermission('VIEW_RECEIPTS'),
  validateParams(ReceiptVerifyParam),
  catchAsync(async (req: any, res) => {
    const tokenOrNumber = String(req.params.tokenOrNumber || '').trim();
    const row: any = await prisma.receipt.findFirst({
      where: { OR: [
        { verificationToken: tokenOrNumber },
        { receiptNumber: tokenOrNumber },
      ]},
      include: {
        student: { select: { id: true, firstName: true, lastName: true, email: true, matricNumber: true } },
        invoice: { include: { fee: { select: { id: true, name: true, feeCode: true } } } },
        transaction: { select: { reference: true, paystackReference: true, alatpayReference: true, paystackChannel: true, gateway: true, type: true, amount: true, status: true, createdAt: true } },
      },
    });

    const brand = await buildBranding();

    if (!row) {
      res.status(404).json({
        status: 'fail',
        verified: false,
        message: 'Receipt not found or verification token invalid',
        branding: brand,
      });
      return;
    }

    res.status(200).json({
      status: 'success',
      verified: !row.isVoided,
      data: {
        id: row.id,
        receiptNumber: row.receiptNumber,
        verificationToken: row.verificationToken,
        paidAmount: Number(row.paidAmount),
        paidAt: row.paidAt,
        isVoided: row.isVoided,
        voidedAt: row.voidedAt || null,
        paymentChannel: row.paymentChannel,
        paymentMethodDetail: row.paymentMethodDetail,
        paystackReference: row.paystackReference || null,
        alatpayReference: (row.transaction?.alatpayReference) || null,
        student: row.student,
        invoice: row.invoice ? {
          id: row.invoice.id,
          invoiceNumber: row.invoice.invoiceNumber || null,
          dueDate: row.invoice.dueDate || null,
          session: row.invoice.session || null,
          semester: row.invoice.semester || null,
          fee: row.invoice.fee ? { name: row.invoice.fee.name, feeCode: row.invoice.fee.feeCode } : null,
        } : null,
        transaction: row.transaction,
      },
      branding: brand,
    });
  }),
);

// -----------------------------------------------------------------------------
// EMAIL: Templates configuration + delivery logs + resend credentials
// (mounted after protect/restrictTo(ADMIN))
// -----------------------------------------------------------------------------

const resendCredentialsLimiter = rateLimit({
  windowMs: 15 * 60 * 1000,
  max: (req: Request) => {
    const id = (req.params as any).id;
    void id;
    return 5;
  },
  standardHeaders: true,
  legacyHeaders: false,
  keyGenerator: (req: Request) => {
    const uid = (req as any).user?.id ?? 'anon';
    const targetId = (req.params as any).id ?? 'all';
    return `resend-creds:${uid}:${targetId}`;
  },
  message: { status: 'fail', message: 'Too many credential resend requests. Please try again in 15 minutes.' },
});

const emailTypeValues: readonly string[] = Object.values(EmailType);
const emailStatusValues: readonly string[] = Object.values(EmailDeliveryStatus);

const TemplateKeyParam = z.object({ templateKey: z.string().min(1).max(100).trim() });
// 1. GET template by key (ADMIN)
router.get('/email-templates/:templateKey', validateParams(TemplateKeyParam), catchAsync(async (req: Request, res: Response) => {
  const key = String((req.params as any).templateKey || '').trim();
  if (!key) return res.status(400).json({ status: 'fail', message: 'templateKey required' });
  const data = await EmailTemplateService.getByKey(key);
  res.json({ status: 'success', data });
}));

// 2. PATCH template by key (ADMIN)
router.patch('/email-templates/:templateKey', validateParams(TemplateKeyParam), validateBody(EmailTemplateConfigPatchSchema), catchAsync(async (req: Request, res: Response) => {
  const key = String((req.params as any).templateKey || '').trim();
  if (!key) return res.status(400).json({ status: 'fail', message: 'templateKey required' });
  const actorId = Number((req as any).user?.id);
  const before = await EmailTemplateService.getByKey(key);
  const updated = await EmailTemplateService.updateByKey(key, req.body as any, { updatedById: Number.isFinite(actorId) ? actorId : undefined });

  const actor = Number.isFinite(actorId) ? actorId : null;
  try {
    await prisma.auditLog.create({
      data: {
        action: 'EMAIL_TEMPLATE_UPDATED',
        entityType: 'EMAIL_TEMPLATE',
        entityId: key,
        userId: actor,
        oldValue: { before: { subject: before.subjectLine, greeting: before.greeting, buttonLabel: before.buttonLabel } } as any,
        newValue: { updatedFields: Object.keys(req.body || {}) } as any,
        details: { templateKey: key, changedFields: Object.keys(req.body || {}) } as any,
        ipAddress: reqIp(req),
        userAgent: reqUa(req),
      },
    });
  } catch { /* ignore */ }
  const data = await EmailTemplateService.getByKey(key);
  void updated;
  res.json({ status: 'success', data });
}));

// Helpers for BigInt JSON serialization (Prisma BIGINT primary keys cannot serialize to JSON)
function stringifyBigintsDeep(v: any): any {
  if (typeof v === 'bigint') return v.toString();
  if (v === null || v === undefined) return v;
  if (typeof v !== 'object') return v;
  if (Array.isArray(v)) return v.map(stringifyBigintsDeep);
  const out: any = {};
  for (const k of Object.keys(v)) out[k] = stringifyBigintsDeep((v as any)[k]);
  return out;
}

// Middleware-like allow-list guard: specific email endpoints accessible to ADMIN *or* BURSARY
// (must run before the global restrictTo('ADMIN'))
function allowAdminOrBursary(req: Request, res: Response, next: any) {
  const role = String((req as any).user?.role || '');
  if (role !== 'ADMIN' && role !== 'BURSARY') {
    return res.status(403).json({ status: 'fail', message: 'Requires ADMIN or BURSARY role' });
  }
  next();
}
function allowAdminOnly(req: Request, res: Response, next: any) {
  const role = String((req as any).user?.role || '');
  if (role !== 'ADMIN') {
    return res.status(403).json({ status: 'fail', message: 'Requires ADMIN role' });
  }
  next();
}

// Helpers for PII mask
function maskEmail(emailLike: string): string {
  const s = String(emailLike || '');
  const at = s.lastIndexOf('@');
  if (at <= 1) return s.length ? '*'.repeat(Math.max(1, s.length)) : s;
  const first = s[0];
  const user = s.slice(1, at);
  const domain = s.slice(at);
  return `${first}${'*'.repeat(Math.max(1, user.length))}${domain}`;
}
function maskMatric(matric: string | null | undefined): string | null {
  if (!matric) return matric ?? null;
  const s = String(matric);
  if (s.length <= 3) return '*'.repeat(s.length);
  return `...${s.slice(-3)}`;
}
function maskDeliveryLogRow(row: any, viewerRole: string) {
  let r: any = stringifyBigintsDeep(row);
  if (viewerRole !== 'ADMIN') {
    r.toAddress = maskEmail(r.toAddress);
    if (r.recipient && typeof r.recipient === 'object' && r.recipient !== null) {
      const rec = { ...r.recipient };
      rec.matricNumber = maskMatric(rec.matricNumber);
      if (rec.email) rec.email = maskEmail(rec.email);
      if (rec.firstName) rec.firstName = viewerRole === 'BURSARY' ? rec.firstName : '*'.repeat(String(rec.firstName).length);
      r.recipient = rec;
    }
  }
  return r;
}

// 3. GET delivery logs list (ADMIN; Bursary sees masked PII)
const emailDeliveryLogsListSchema = z.object({
  page: z.coerce.number().int().min(1).max(1000000).default(1),
  pageSize: z.coerce.number().int().min(1).max(200).default(25),
  emailType: z.string().optional(),
  status: z.string().optional(),
  toAddressContains: z.string().max(254).optional(),
  recipientId: z.coerce.number().int().optional(),
  studentImportId: z.coerce.number().int().optional(),
});
router.get('/email-delivery-logs', validateQuery(emailDeliveryLogsListSchema), catchAsync(async (req: Request, res: Response) => {
  const q = (req.query as any);
  const page = Number(q.page) || 1;
  const pageSize = Math.min(200, Math.max(1, Number(q.pageSize) || 25));
  const skip = (page - 1) * pageSize;
  const viewerRole = String((req as any).user?.role || '');

  const where: any = {};
  if (q.emailType && emailTypeValues.includes(String(q.emailType).toUpperCase())) {
    where.emailType = String(q.emailType).toUpperCase();
  }
  if (q.status && emailStatusValues.includes(String(q.status).toUpperCase())) {
    where.status = String(q.status).toUpperCase();
  }
  if (typeof q.toAddressContains === 'string' && q.toAddressContains.trim().length) {
    where.toAddress = { contains: q.toAddressContains.trim(), mode: 'insensitive' };
  }
  if (Number.isFinite(Number(q.recipientId))) {
    where.recipientId = Number(q.recipientId);
  }
  if (Number.isFinite(Number(q.studentImportId))) {
    where.studentImportId = Number(q.studentImportId);
  }

  const [total, rows] = await Promise.all([
    prisma.emailDeliveryLog.count({ where }),
    prisma.emailDeliveryLog.findMany({
      where,
      orderBy: { createdAt: 'desc' },
      skip,
      take: pageSize,
      include: {
        recipient: { select: { id: true, email: true, firstName: true, lastName: true, matricNumber: true } },
        triggeredByAdmin: { select: { id: true, email: true, firstName: true, lastName: true, role: true } },
        studentImport: { select: { id: true, importNumber: true, fileName: true, createdAt: true } },
      },
    }),
  ]);
  const totalPages = Math.max(1, Math.ceil(total / pageSize));
  const mapped = rows.map(r => maskDeliveryLogRow(r, viewerRole));
  res.json({
    status: 'success',
    data: {
      rows: mapped,
      total,
      page,
      pageSize,
      totalPages,
      hasNext: page < totalPages,
    },
  });
}));

// 4. GET single delivery log detail (ADMIN; Bursary sees PII masked)
router.get('/email-delivery-logs/:id', validateParams(z.object({ id: z.union([z.coerce.string().min(1), z.coerce.number().int().min(1)]) })), catchAsync(async (req: Request, res: Response) => {
  const rawId = (req.params as any).id;
  let id: bigint;
  try {
    id = BigInt(String(rawId));
    if (id <= 0n) throw new Error('non-positive');
  } catch {
    return res.status(400).json({ status: 'fail', message: 'Invalid delivery log id' });
  }
  const viewerRole = String((req as any).user?.role || '');
  const row = await prisma.emailDeliveryLog.findUnique({
    where: { id },
    include: {
      recipient: { select: { id: true, email: true, firstName: true, lastName: true, matricNumber: true } },
      triggeredByAdmin: { select: { id: true, email: true, firstName: true, lastName: true, role: true } },
      studentImport: { select: { id: true, importNumber: true, fileName: true, createdAt: true, totalRecords: true, successfulRecords: true } },
    },
  });
  if (!row) return res.status(404).json({ status: 'fail', message: 'Delivery log not found' });
  res.json({ status: 'success', data: maskDeliveryLogRow(row, viewerRole) });
}));

// 5. POST resend credentials (ADMIN, 5/15m per target user per admin)
router.post('/users/:id/resend-credentials', resendCredentialsLimiter, validateParams(z.object({ id: z.coerce.number().int().min(1) })), catchAsync(async (req: Request, res: Response) => {
  const targetId = Number((req.params as any).id);
  const actorId = Number((req as any).user?.id);
  const ip = reqIp(req);
  const ua = reqUa(req);
  if (!Number.isFinite(actorId)) return res.status(401).json({ status: 'fail', message: 'Unauthorized' });
  await StudentService.sendCredentialEmail(targetId, actorId, { forcePasswordReset: true, ip, userAgent: ua });
  // Most recent delivery log for this user is PENDING in DB; return 202.
  const lastLog = await prisma.emailDeliveryLog.findFirst({
    where: { recipientId: targetId, emailType: EmailType.STUDENT_CREDENTIALS },
    orderBy: { createdAt: 'desc' },
    select: { id: true, status: true, attempts: true, createdAt: true },
  });
  res.status(202).json({
    status: 'success',
    data: {
      deliveryLogId: lastLog?.id ? String(lastLog.id) : null,
      queued: true,
      message: 'A new temporary password has been generated and the credentials email queued for delivery.',
    },
  });
}));

export default router;
