// STAGE 5 F5 — Export Centre (R19). Lists recent ReportExport rows.
// Shows: report name, format, status, generated by, date, filters JSON snapshot, row count, file size, download button.
// Export buttons for Excel/PDF of the centre list itself, permission-guarded.

import React, { useEffect, useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import PortalShell from '../../components/PortalShell';
import { useAuth } from '../../context/AuthContext';
import { navCounters, NavCounters } from '../../services/api';
import api from '../../services/api';
import { i18n } from '../../i18n/en';
import {
  ArrowLeft, Download, FileSpreadsheet, FileText,
  Loader2, AlertTriangle, CheckCircle2, XCircle, Clock, Filter,
  ChevronLeft, ChevronRight, FileJson, Eye,
} from 'lucide-react';
import {
  getExportCentre, downloadBlob,
} from '../../services/reportsApi';

type Role = 'BURSARY' | 'ADMIN';
export interface ExportCentrePageProps { role: Role; activePath: string; }

const hasPerm = (p: string, perms?: string[], role?: Role) => {
  if (role === 'ADMIN') return true;
  return perms?.includes(p) ?? false;
};

const fmtBytes = (n: number | null | undefined) => {
  if (n == null || Number.isNaN(Number(n))) return '—';
  const v = Number(n);
  if (v < 1024) return `${v} B`;
  if (v < 1024 * 1024) return `${(v / 1024).toFixed(1)} KB`;
  return `${(v / 1024 / 1024).toFixed(2)} MB`;
};

type StatusBadgeKind = 'PENDING' | 'PROCESSING' | 'COMPLETED' | 'FAILED' | 'QUEUED';
const statusStyle = (s: string): { cls: string; icon: any; label: string } => {
  switch ((s || '').toUpperCase() as StatusBadgeKind) {
    case 'COMPLETED':
      return { cls: 'bg-emerald-50 text-emerald-800 border-emerald-200', icon: CheckCircle2, label: 'Completed' };
    case 'FAILED':
      return { cls: 'bg-red-50 text-red-800 border-red-200', icon: XCircle, label: 'Failed' };
    case 'PROCESSING':
      return { cls: 'bg-sky-50 text-sky-800 border-sky-200', icon: Loader2, label: 'Processing' };
    case 'QUEUED':
    case 'PENDING':
      return { cls: 'bg-amber-50 text-amber-800 border-amber-200', icon: Clock, label: s?.toUpperCase() === 'QUEUED' ? 'Queued' : 'Pending' };
    default:
      return { cls: 'bg-gray-50 text-gray-700 border-gray-200', icon: AlertTriangle, label: s || 'Unknown' };
  }
};

const formatIcon = (fmt: string) => {
  switch ((fmt || '').toUpperCase()) {
    case 'XLSX':
    case 'EXCEL':
      return <FileSpreadsheet className="h-4 w-4 text-emerald-700" />;
    case 'PDF':
      return <FileText className="h-4 w-4 text-rose-700" />;
    default:
      return <FileJson className="h-4 w-4 text-gray-600" />;
  }
};

type ToastKind = 'ok' | 'err' | 'info';
interface ToastState { kind: ToastKind; text: string; }

const ExportCentrePage: React.FC<ExportCentrePageProps> = ({ role, activePath }) => {
  const { user, logout } = useAuth();
  const navigate = useNavigate();
  const userPerms = (user?.permissions as string[] | undefined) ?? [];
  const [navCounts, setNavCounts] = useState<NavCounters>({});
  const [loading, setLoading] = useState(true);
  const [data, setData] = useState<any>(null);
  const [err, setErr] = useState<string | null>(null);
  const [page, setPage] = useState<number>(1);
  const [pageSize] = useState<number>(50);
  const [expandedId, setExpandedId] = useState<number | string | null>(null);
  const [downloadingId, setDownloadingId] = useState<number | string | null>(null);
  const [exporting, setExporting] = useState<'xlsx' | 'pdf' | null>(null);
  const [toast, setToast] = useState<ToastState | null>(null);

  useEffect(() => { navCounters().then(setNavCounts).catch(() => {}); }, []);

  const fetchData = () => {
    let mounted = true; setLoading(true); setErr(null);
    getExportCentre({ page, pageSize })
      .then((d) => { if (mounted) setData(d); })
      .catch((e) => { if (mounted) setErr(String(e?.message ?? e).slice(0, 250)); })
      .finally(() => { if (mounted) setLoading(false); });
    return () => { mounted = false; };
  };

  useEffect(fetchData, [page, pageSize]);

  const rows: any[] = useMemo(() => data?.rows ?? data ?? [], [data]);
  const total: number | undefined = data?.total;

  const brand = role === 'BURSARY' ? i18n.portals.bursary.dashboardBrand : i18n.portals.admin.dashboardBrand;
  const userText = role === 'BURSARY'
    ? `Bursary: ${user?.firstName ?? ''} ${user?.lastName ?? ''}`.trim()
    : i18n.portals.admin.dashboardGreeting(`${user?.firstName ?? ''} ${user?.lastName ?? ''}`.trim() || 'Admin');

  const fireToast = (kind: ToastKind, text: string, ms = 4500) => {
    setToast({ kind, text });
    window.setTimeout(() => setToast((t) => (t && t.text === text ? null : t)), ms);
  };

  const canXlsx = hasPerm('REPORTS_EXPORT_EXCEL', userPerms, role);
  const canPdf = hasPerm('REPORTS_EXPORT_PDF', userPerms, role);

  const downloadExport = async (row: any) => {
    const id = row.reportUuid || row.uuid || row.id;
    if (!id) { fireToast('err', 'No report UUID to download'); return; }
    try {
      setDownloadingId(id);
      const resp = await api.get(`/reports/download/${encodeURIComponent(String(id))}`, { responseType: 'blob', timeout: 120000 });
      if (resp.data instanceof Blob) {
        const fname = row.reportName ? `${row.reportName.replace(/\s+/g, '_')}_${id.slice(0, 8)}` : `export_${id}`;
        const ext = String(row.format || 'xlsx').toLowerCase() === 'pdf' ? 'pdf' : 'xlsx';
        downloadBlob(resp.data, `${fname}.${ext}`);
        fireToast('info', 'Download started');
      }
    } catch (e: any) {
      fireToast('err', 'Download failed: ' + String(e?.message ?? e).slice(0, 150));
    } finally {
      setDownloadingId(null);
    }
  };

  const runExport = async (format: 'xlsx' | 'pdf') => {
    const perm = format === 'xlsx' ? 'REPORTS_EXPORT_EXCEL' : 'REPORTS_EXPORT_PDF';
    if (!hasPerm(perm, userPerms, role)) { fireToast('err', `Missing permission ${perm}`); return; }
    try {
      setExporting(format);
      const resp = await api.post(`/reports/export-centre/export?format=${format}`, {}, { responseType: 'blob', timeout: 120000 });
      const ct = String(resp.headers?.['content-type'] ?? '') as string;
      if ((ct.includes('application/json') || resp.status === 202) && resp.data instanceof Blob) {
        const txt = await (resp.data as Blob).text();
        try {
          const parsed = JSON.parse(txt);
          const jobId = parsed.jobId ? ` JobId: ${parsed.jobId}` : '';
          fireToast('ok', `Queued! You will receive an email when ready.${jobId}`, 6500);
        } catch {
          fireToast('info', txt || 'Queued for processing');
        }
      } else if (resp.data instanceof Blob) {
        downloadBlob(resp.data, `export-centre_${Date.now()}.${format === 'xlsx' ? 'xlsx' : 'pdf'}`);
        fireToast('info', `Downloaded ${format.toUpperCase()}`);
      }
    } catch (e: any) {
      fireToast('err', 'Export failed: ' + String(e?.message ?? e).slice(0, 150));
    } finally {
      setExporting(null);
    }
  };

  const goPage = (delta: number) => setPage((p) => Math.max(1, p + delta));

  const content = (
    <div className="px-6 py-6 md:px-8 lg:px-10">
      {toast && (
        <div className={`fixed top-5 right-5 z-[100] inline-flex items-center gap-2 rounded-xl border px-4 py-3 text-sm shadow-lg max-w-md ${
          toast.kind === 'ok' ? 'bg-emerald-50 text-emerald-800 border-emerald-200'
          : toast.kind === 'err' ? 'bg-red-50 text-red-800 border-red-200'
          : 'bg-sky-50 text-sky-800 border-sky-200'
        }`}>
          {toast.kind === 'ok' ? <CheckCircle2 className="h-4 w-4 shrink-0" /> : <AlertTriangle className="h-4 w-4 shrink-0" />}
          <span className="font-medium">{toast.text}</span>
          <button type="button" onClick={() => setToast(null)} className="ml-1 opacity-60 hover:opacity-100">
            <Filter className="h-3.5 w-3.5" />
          </button>
        </div>
      )}

      <div className="mb-6 flex flex-wrap items-end justify-between gap-3">
        <div>
          <button type="button" onClick={() => navigate('/bursary/reports/centre')} className="inline-flex items-center gap-1 text-xs text-gray-500 hover:text-gray-800 mb-2">
            <ArrowLeft className="h-3 w-3" /> Back to Reports Centre
          </button>
          <div className="text-xs text-sky-700 font-semibold tracking-widest mb-1">ACCOUNTING • EXPORT CENTRE</div>
          <h1 className="text-2xl font-extrabold text-gray-900">Export Centre</h1>
          <p className="text-sm text-gray-500 mt-1">All recent report exports: status, filters snapshot, download links. Rows persist for 60 days.</p>
        </div>
        <div className="flex items-center gap-2">
          <button
            type="button"
            onClick={() => runExport('xlsx')}
            disabled={!!exporting || !canXlsx}
            title={canXlsx ? 'Download Excel' : 'Missing REPORTS_EXPORT_EXCEL permission'}
            className="inline-flex items-center gap-2 px-3 py-2 rounded-lg text-sm font-semibold bg-emerald-700 hover:bg-emerald-800 text-white disabled:opacity-50 disabled:cursor-not-allowed"
          >
            {exporting === 'xlsx' ? <Loader2 className="h-4 w-4 animate-spin" /> : <FileSpreadsheet className="h-4 w-4" />}
            Download Excel
          </button>
          <button
            type="button"
            onClick={() => runExport('pdf')}
            disabled={!!exporting || !canPdf}
            title={canPdf ? 'Download PDF' : 'Missing REPORTS_EXPORT_PDF permission'}
            className="inline-flex items-center gap-2 px-3 py-2 rounded-lg text-sm font-semibold bg-rose-700 hover:bg-rose-800 text-white disabled:opacity-50 disabled:cursor-not-allowed"
          >
            {exporting === 'pdf' ? <Loader2 className="h-4 w-4 animate-spin" /> : <FileText className="h-4 w-4" />}
            Download PDF
          </button>
        </div>
      </div>

      {err && (
        <div className="mb-5 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-800 font-mono">{err}</div>
      )}

      <div className="bg-white border border-gray-200 rounded-2xl shadow-sm overflow-hidden">
        <div className="flex items-center justify-between px-5 py-3 border-b border-gray-100 flex-wrap gap-3">
          <div className="text-sm font-semibold text-gray-800 flex items-center gap-2">
            <span className="text-gray-400 mr-1">Recent Exports</span>
            <span className="inline-flex items-center rounded-full bg-gray-100 text-gray-700 px-2 py-0.5 text-xs font-mono">
              {rows.length.toLocaleString()} rows
            </span>
            {loading && <span className="inline-flex items-center gap-1 text-xs text-gray-500"><Loader2 className="h-3 w-3 animate-spin" />Loading…</span>}
          </div>
          <div className="text-xs text-gray-500">
            Page {page} • {pageSize} / page{total != null ? ` • ${Number(total).toLocaleString()} total` : ''}
          </div>
        </div>

        {!Array.isArray(rows) || rows.length === 0 ? (
          <div className="p-10 text-center text-gray-500 text-sm">
            <FileText className="h-10 w-10 text-gray-300 mx-auto mb-2" />
            No exports yet. Run any report and click <strong>Export Excel</strong> or <strong>Export PDF</strong> to populate this list.
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="min-w-full text-xs">
              <thead className="bg-gray-50">
                <tr>
                  <th className="px-3 py-2 font-semibold text-gray-700 text-left border-b whitespace-nowrap">Report</th>
                  <th className="px-3 py-2 font-semibold text-gray-700 text-left border-b whitespace-nowrap">Format</th>
                  <th className="px-3 py-2 font-semibold text-gray-700 text-left border-b whitespace-nowrap">Generated</th>
                  <th className="px-3 py-2 font-semibold text-gray-700 text-left border-b whitespace-nowrap">By</th>
                  <th className="px-3 py-2 font-semibold text-gray-700 text-right border-b whitespace-nowrap">Rows</th>
                  <th className="px-3 py-2 font-semibold text-gray-700 text-right border-b whitespace-nowrap">Size</th>
                  <th className="px-3 py-2 font-semibold text-gray-700 text-left border-b whitespace-nowrap">Status</th>
                  <th className="px-3 py-2 font-semibold text-gray-700 text-center border-b whitespace-nowrap">Actions</th>
                </tr>
              </thead>
              <tbody>
                {rows.map((r: any) => {
                  const id = r.reportUuid || r.uuid || r.id;
                  const isExp = expandedId === id;
                  const s = statusStyle(r.status);
                  const StatIcon = s.icon;
                  const disabledDl = (r.status || '').toUpperCase() !== 'COMPLETED';
                  return (
                    <React.Fragment key={String(id ?? (r as any).index ?? Math.random())}>
                      <tr className="border-b border-gray-50 hover:bg-amber-50/40">
                        <td className="px-3 py-2">
                          <div className="font-semibold text-gray-800">{r.reportName || r.reportType || '—'}</div>
                          <div className="text-[10px] text-gray-500 font-mono">{r.reportType || ''}</div>
                        </td>
                        <td className="px-3 py-2 whitespace-nowrap">
                          <span className="inline-flex items-center gap-1">
                            {formatIcon(r.format)} <span className="font-mono uppercase">{r.format || '—'}</span>
                          </span>
                        </td>
                        <td className="px-3 py-2 whitespace-nowrap text-gray-600">
                          {r.createdAt ? new Date(r.createdAt).toLocaleString() : r.dateRangeStart || '—'}
                        </td>
                        <td className="px-3 py-2 whitespace-nowrap">
                          <div className="text-gray-800">{r.generatedByName || r.generatedBy || (r.generatedById ? `User #${r.generatedById}` : '—')}</div>
                        </td>
                        <td className="px-3 py-2 text-right tabular-nums font-mono">{r.rowCount != null ? Number(r.rowCount).toLocaleString() : '—'}</td>
                        <td className="px-3 py-2 text-right tabular-nums font-mono">{fmtBytes(r.fileSizeBytes)}</td>
                        <td className="px-3 py-2 whitespace-nowrap">
                          <span className={`inline-flex items-center gap-1 px-2 py-0.5 rounded-full border text-[11px] font-semibold ${s.cls}`}>
                            <StatIcon className={`h-3 w-3 ${(s.label === 'Processing') ? 'animate-spin' : ''}`} />
                            {s.label}
                          </span>
                          {r.jobId && <div className="text-[10px] font-mono text-gray-500 mt-1">Job: {String(r.jobId).slice(0, 12)}…</div>}
                        </td>
                        <td className="px-3 py-2 whitespace-nowrap text-center">
                          <div className="inline-flex items-center gap-1">
                            <button
                              type="button"
                              onClick={() => setExpandedId(isExp ? null : id)}
                              title="View filters snapshot"
                              className="inline-flex items-center justify-center h-7 w-7 rounded-md text-gray-600 hover:bg-gray-100 border border-gray-200"
                            >
                              <Eye className="h-3.5 w-3.5" />
                            </button>
                            <button
                              type="button"
                              onClick={() => downloadExport(r)}
                              disabled={disabledDl || downloadingId === id || !!r.downloadUrl === false && !id}
                              title={disabledDl ? 'Download available only when COMPLETED' : 'Download file'}
                              className="inline-flex items-center justify-center h-7 px-2 gap-1 rounded-md text-xs font-semibold bg-amber-600 hover:bg-amber-700 text-white disabled:opacity-40 disabled:cursor-not-allowed"
                            >
                              {downloadingId === id ? <Loader2 className="h-3 w-3 animate-spin" /> : <Download className="h-3 w-3" />}
                              Download
                            </button>
                          </div>
                        </td>
                      </tr>
                      {isExp && (
                        <tr className="border-b border-gray-50 bg-gray-50">
                          <td colSpan={8} className="px-4 py-3">
                            <div className="grid grid-cols-1 md:grid-cols-3 gap-3 text-[11px]">
                              <div>
                                <div className="text-[10px] uppercase tracking-wider font-bold text-gray-500 mb-1">Period</div>
                                <div className="font-mono text-gray-700">
                                  {r.dateRangeStart || r.dateFrom ? `${r.dateRangeStart || r.dateFrom} → ${r.dateRangeEnd || r.dateTo || '—'}` : '—'}
                                </div>
                              </div>
                              <div>
                                <div className="text-[10px] uppercase tracking-wider font-bold text-gray-500 mb-1">Report UUID</div>
                                <div className="font-mono text-gray-700 break-all">{r.reportUuid || r.uuid || '—'}</div>
                              </div>
                              <div>
                                <div className="text-[10px] uppercase tracking-wider font-bold text-gray-500 mb-1">Error (if any)</div>
                                <div className="font-mono text-red-700">{r.errorMessage || r.error || '—'}</div>
                              </div>
                              <div className="md:col-span-3">
                                <div className="text-[10px] uppercase tracking-wider font-bold text-gray-500 mb-1">
                                  Filters Snapshot (JSON — exact filters sent to aggregator at export time)
                                </div>
                                <pre className="bg-white border border-gray-200 rounded-lg p-3 text-gray-700 overflow-x-auto font-mono whitespace-pre-wrap break-words max-h-[280px]">
{r.filters ? (typeof r.filters === 'string' ? r.filters : JSON.stringify(r.filters, null, 2)) : '{}'}
                                </pre>
                              </div>
                            </div>
                          </td>
                        </tr>
                      )}
                    </React.Fragment>
                  );
                })}
              </tbody>
            </table>
          </div>
        )}

        <div className="flex items-center justify-between px-5 py-3 border-t border-gray-100 text-xs text-gray-600 font-medium">
          <span className="text-gray-500">
            {total != null ? `${Math.min(page * pageSize, Number(total)).toLocaleString()} of ${Number(total).toLocaleString()}` : `Page ${page}`}
          </span>
          <div className="flex items-center gap-1">
            <button className="px-2 py-1 rounded border border-gray-200 hover:bg-gray-50 disabled:opacity-40"
              disabled={page <= 1 || loading} onClick={() => goPage(-1)}>
              <ChevronLeft className="h-3 w-3" />
            </button>
            <span className="px-2 font-mono tabular-nums">{page}</span>
            <button className="px-2 py-1 rounded border border-gray-200 hover:bg-gray-50 disabled:opacity-40"
              disabled={total != null ? page * pageSize >= Number(total) : false} onClick={() => goPage(+1)}>
              <ChevronRight className="h-3 w-3" />
            </button>
          </div>
        </div>
      </div>
    </div>
  );

  return (
    <PortalShell role={role} activePath={activePath} brand={brand} userText={userText} userEmail={user?.email}
      onLogout={logout} userPermissions={userPerms} navCounters={navCounts} showGlobalSearch>
      {content}
    </PortalShell>
  );
};

export default ExportCentrePage;
