/**
 * STAGE 4b — Export column catalog.
 * Each key → ordered array of column descriptors used by both XLSX streaming writer
 * and the PDF detailed table HTML builder. Column order matches spec column lists.
 */

export type Column =
  | { key: string; header: string; isMoney?: boolean; isNum?: boolean; isMonospace?: boolean; width?: number }
  | { key: string; header: string; isMoney?: boolean; isNum?: boolean; isMonospace?: boolean; width?: number };

export const REPORT_COLUMN_KEYS = [
  'key_value',
  'daily',
  'monthly',
  'payers_register',
  'revenue_by_bill',
  'payment_register',
  'student_ledger',
  'bill_performance',
  'debtors',
  'hierarchical',
  'gateway',
  'settlement',
  'exceptions',
  'refunds',
  'charges',
  'gl',
  'receipts',
  'status_mix',
  'comparative',
  'scheduled',
  'export_audit',
] as const;

export type ReportColumnsCatalogKey = typeof REPORT_COLUMN_KEYS[number];

export const EXPORT_COLUMN_CATALOG: Record<ReportColumnsCatalogKey, Column[]> = {
  key_value: [
    { key: 'metric', header: 'Metric' },
    { key: 'value', header: 'Value', isNum: true },
  ],
  daily: [
    { key: 'date', header: 'Date', width: 14 },
    { key: 'txCount', header: 'Tx Count', isNum: true },
    { key: 'studentCount', header: 'Unique Payers', isNum: true },
    { key: 'gross', header: 'Gross (NGN)', isMoney: true },
    { key: 'convenienceFee', header: 'Conv. Fee', isMoney: true },
    { key: 'serviceCharge', header: 'Svc Charge', isMoney: true },
    { key: 'gatewayFee', header: 'Gateway Fee', isMoney: true },
    { key: 'refunds', header: 'Refunds', isMoney: true },
    { key: 'net', header: 'Net Collected', isMoney: true },
  ],
  monthly: [
    { key: 'month', header: 'Month', width: 14 },
    { key: 'txCount', header: 'Tx Count', isNum: true },
    { key: 'uniquePayers', header: 'Unique Payers', isNum: true },
    { key: 'gross', header: 'Gross (NGN)', isMoney: true },
    { key: 'charges', header: 'Charges', isMoney: true },
    { key: 'refunds', header: 'Refunds', isMoney: true },
    { key: 'net', header: 'Net', isMoney: true },
  ],
  payers_register: [
    { key: 'paymentDate', header: 'Payment Date', width: 14 },
    { key: 'studentName', header: 'Student' },
    { key: 'matricNumber', header: 'Matric No.', isMonospace: true, width: 16 },
    { key: 'college', header: 'College' },
    { key: 'department', header: 'Department' },
    { key: 'programme', header: 'Programme' },
    { key: 'level', header: 'Level' },
    { key: 'session', header: 'Session' },
    { key: 'paymentRef', header: 'Payment Ref', isMonospace: true },
    { key: 'gatewayRef', header: 'Gateway Ref', isMonospace: true },
    { key: 'billName', header: 'Bill' },
    { key: 'baseAmount', header: 'Base Amount', isMoney: true },
    { key: 'convFee', header: 'Conv. Fee', isMoney: true },
    { key: 'svcFee', header: 'Svc Charge', isMoney: true },
    { key: 'gwFee', header: 'Gateway Fee', isMoney: true },
    { key: 'totalPaid', header: 'Total Paid', isMoney: true },
    { key: 'provider', header: 'Provider' },
    { key: 'status', header: 'Status' },
    { key: 'receiptNo', header: 'Receipt No.', isMonospace: true },
  ],
  revenue_by_bill: [
    { key: 'revenueItem', header: 'Revenue Item (Bill/Category)' },
    { key: 'numPayers', header: 'Num Payers', isNum: true },
    { key: 'expectedAmount', header: 'Expected (NGN)', isMoney: true },
    { key: 'collected', header: 'Collected', isMoney: true },
    { key: 'outstanding', header: 'Outstanding', isMoney: true },
    { key: 'collectionPct', header: 'Collection %', isNum: true },
  ],
  payment_register: [
    { key: 'transactionId', header: 'Tx ID', isNum: true, width: 10 },
    { key: 'createdAt', header: 'Payment Date', width: 16 },
    { key: 'studentName', header: 'Student' },
    { key: 'matricNumber', header: 'Matric No.', isMonospace: true },
    { key: 'college', header: 'College' },
    { key: 'department', header: 'Department' },
    { key: 'programme', header: 'Programme' },
    { key: 'level', header: 'Level' },
    { key: 'session', header: 'Session' },
    { key: 'billName', header: 'Bill' },
    { key: 'category', header: 'Category' },
    { key: 'baseAmount', header: 'Base', isMoney: true },
    { key: 'convenienceFee', header: 'Conv', isMoney: true },
    { key: 'serviceCharge', header: 'Svc', isMoney: true },
    { key: 'gatewayFee', header: 'GW', isMoney: true },
    { key: 'totalAmount', header: 'Total Paid', isMoney: true },
    { key: 'provider', header: 'Provider' },
    { key: 'status', header: 'Status' },
    { key: 'transactionReference', header: 'Tx Ref', isMonospace: true },
    { key: 'gatewayReference', header: 'Gateway Ref', isMonospace: true },
    { key: 'receiptNumber', header: 'Receipt No.', isMonospace: true },
    { key: 'paidAt', header: 'Receipt Date', width: 16 },
  ],
  student_ledger: [
    { key: 'date', header: 'Date', width: 14 },
    { key: 'description', header: 'Description' },
    { key: 'bill', header: 'Bill' },
    { key: 'debit', header: 'Debit (NGN)', isMoney: true },
    { key: 'credit', header: 'Credit (NGN)', isMoney: true },
    { key: 'balance', header: 'Balance', isMoney: true },
    { key: 'ref', header: 'Ref', isMonospace: true },
    { key: 'receipt', header: 'Receipt', isMonospace: true },
  ],
  bill_performance: [
    { key: 'billId', header: 'Bill ID', isNum: true, width: 8 },
    { key: 'billName', header: 'Bill' },
    { key: 'category', header: 'Category' },
    { key: 'assigned', header: 'Students Assigned', isNum: true },
    { key: 'expectedAmount', header: 'Expected (NGN)', isMoney: true },
    { key: 'fullPaidCount', header: 'Fully Paid', isNum: true },
    { key: 'partialPaidCount', header: 'Partially Paid', isNum: true },
    { key: 'unpaidCount', header: 'Unpaid', isNum: true },
    { key: 'collected', header: 'Collected', isMoney: true },
    { key: 'outstanding', header: 'Outstanding', isMoney: true },
    { key: 'collectionPct', header: 'Collection %', isNum: true },
  ],
  debtors: [
    { key: 'studentId', header: 'St. ID', isNum: true, width: 8 },
    { key: 'studentName', header: 'Student' },
    { key: 'matricNumber', header: 'Matric No.', isMonospace: true },
    { key: 'college', header: 'College' },
    { key: 'department', header: 'Department' },
    { key: 'programme', header: 'Programme' },
    { key: 'level', header: 'Level' },
    { key: 'session', header: 'Session' },
    { key: 'billName', header: 'Bill' },
    { key: 'dueAmount', header: 'Due (NGN)', isMoney: true },
    { key: 'paidAmount', header: 'Paid', isMoney: true },
    { key: 'outstanding', header: 'Outstanding', isMoney: true },
    { key: 'paymentStatus', header: 'Status' },
  ],
  hierarchical: [
    { key: 'level', header: 'Level' },
    { key: 'nodeId', header: 'Node ID', isNum: true, width: 8 },
    { key: 'nodeName', header: 'Node' },
    { key: 'parentName', header: 'Parent' },
    { key: 'txCount', header: 'Tx Count', isNum: true },
    { key: 'uniquePayers', header: 'Unique Payers', isNum: true },
    { key: 'gross', header: 'Gross (NGN)', isMoney: true },
    { key: 'net', header: 'Net', isMoney: true },
    { key: 'collectionPctOfGrand', header: '% of Grand', isNum: true },
  ],
  gateway: [
    { key: 'provider', header: 'Provider' },
    { key: 'successCount', header: 'Success', isNum: true },
    { key: 'failCount', header: 'Failed', isNum: true },
    { key: 'pendingCount', header: 'Pending', isNum: true },
    { key: 'gross', header: 'Gross (NGN)', isMoney: true },
    { key: 'gatewayFees', header: 'Gateway Fees', isMoney: true },
    { key: 'refunds', header: 'Refunds', isMoney: true },
    { key: 'expectedSettlement', header: 'Expected Settlement', isMoney: true },
    { key: 'reconciledCount', header: 'Reconciled Txs', isNum: true },
    { key: 'variance', header: 'Variance', isMoney: true },
  ],
  settlement: [
    { key: 'transactionReference', header: 'Tx Ref', isMonospace: true },
    { key: 'provider', header: 'Provider' },
    { key: 'paymentDate', header: 'Payment Date', width: 14 },
    { key: 'paymentAmount', header: 'Payment (NGN)', isMoney: true },
    { key: 'gatewayFee', header: 'GW Fee', isMoney: true },
    { key: 'expectedSettlement', header: 'Expected Settlement', isMoney: true },
    { key: 'settlementDate', header: 'Settlement Date', width: 16 },
    { key: 'settlementRef', header: 'Settlement Ref', isMonospace: true },
    { key: 'actualSettlement', header: 'Actual Settlement', isMoney: true },
    { key: 'variance', header: 'Variance', isMoney: true },
    { key: 'reconciliationStatus', header: 'Recon Status' },
  ],
  exceptions: [
    { key: 'exceptionKind', header: 'Exception Code' },
    { key: 'exceptionLabel', header: 'Exception Label' },
    { key: 'transactionId', header: 'Tx ID', isNum: true, width: 8 },
    { key: 'transactionReference', header: 'Tx Ref', isMonospace: true },
    { key: 'gatewayReference', header: 'Gateway Ref', isMonospace: true },
    { key: 'studentName', header: 'Student' },
    { key: 'matricNumber', header: 'Matric No.', isMonospace: true },
    { key: 'receiptNumber', header: 'Receipt', isMonospace: true },
    { key: 'amount', header: 'Amount', isMoney: true },
    { key: 'note', header: 'Note / Detail' },
  ],
  refunds: [
    { key: 'refundDate', header: 'Refund Date', width: 14 },
    { key: 'studentName', header: 'Student' },
    { key: 'matricNumber', header: 'Matric No.', isMonospace: true },
    { key: 'originalTxRef', header: 'Orig Tx Ref', isMonospace: true },
    { key: 'originalAmount', header: 'Orig Amount', isMoney: true },
    { key: 'refundAmount', header: 'Refund Amount', isMoney: true },
    { key: 'reason', header: 'Reason' },
    { key: 'requestedByName', header: 'Requested By' },
    { key: 'approvedByName', header: 'Approved By' },
    { key: 'provider', header: 'Provider' },
    { key: 'providerRefundRef', header: 'Refund Ref', isMonospace: true },
    { key: 'status', header: 'Status' },
  ],
  charges: [
    { key: 'period', header: 'Period', width: 14 },
    { key: 'basePayment', header: 'Base Payment (NGN)', isMoney: true },
    { key: 'convFee', header: 'Conv. Fee', isMoney: true },
    { key: 'svcCharge', header: 'Svc Charge', isMoney: true },
    { key: 'gwFee', header: 'Gateway Fee', isMoney: true },
    { key: 'totalCharged', header: 'Total Charged', isMoney: true },
    { key: 'netRevenue', header: 'Net Revenue', isMoney: true },
  ],
  gl: [
    { key: 'transactionDate', header: 'Date', width: 14 },
    { key: 'entryType', header: 'Entry Type' },
    { key: 'account', header: 'Account' },
    { key: 'counterparty', header: 'Counterparty' },
    { key: 'description', header: 'Description' },
    { key: 'debit', header: 'Debit (NGN)', isMoney: true },
    { key: 'credit', header: 'Credit (NGN)', isMoney: true },
    { key: 'transactionId', header: 'Tx ID', isNum: true, width: 8 },
    { key: 'transactionRef', header: 'Tx Ref', isMonospace: true },
    { key: 'receiptId', header: 'Receipt', isMonospace: true },
    { key: 'userId', header: 'User ID', isNum: true, width: 8 },
  ],
  receipts: [
    { key: 'receiptNumber', header: 'Receipt No.', isMonospace: true },
    { key: 'date', header: 'Date', width: 14 },
    { key: 'studentName', header: 'Student' },
    { key: 'matricNumber', header: 'Matric No.', isMonospace: true },
    { key: 'billName', header: 'Bill' },
    { key: 'baseAmount', header: 'Base', isMoney: true },
    { key: 'charges', header: 'Charges', isMoney: true },
    { key: 'totalAmount', header: 'Total', isMoney: true },
    { key: 'transactionRef', header: 'Tx Ref', isMonospace: true },
    { key: 'provider', header: 'Provider' },
    { key: 'voidedFlag', header: 'Voided?' },
    { key: 'duplicateFlag', header: 'Duplicate?' },
    { key: 'exceptionReceiptNoPayment', header: 'No Payment Match?' },
  ],
  status_mix: [
    { key: 'status', header: 'Status' },
    { key: 'count', header: 'Count', isNum: true },
    { key: 'amount', header: 'Amount (NGN)', isMoney: true },
    { key: 'includedInRevenue', header: 'In Revenue?' },
    { key: 'sharePct', header: 'Share %', isNum: true },
  ],
  comparative: [
    { key: 'bucket', header: 'Bucket' },
    { key: 'period', header: 'Period' },
    { key: 'txCount', header: 'Tx Count', isNum: true },
    { key: 'uniquePayers', header: 'Unique Payers', isNum: true },
    { key: 'gross', header: 'Gross (NGN)', isMoney: true },
    { key: 'refunds', header: 'Refunds', isMoney: true },
    { key: 'net', header: 'Net', isMoney: true },
    { key: 'deltaNet', header: 'Δ Net', isMoney: true },
    { key: 'deltaNetPct', header: 'Δ %', isNum: true },
  ],
  scheduled: [
    { key: 'id', header: 'Job ID', isNum: true, width: 8 },
    { key: 'name', header: 'Job Name' },
    { key: 'reportType', header: 'Report Type' },
    { key: 'frequency', header: 'Frequency' },
    { key: 'cronExpression', header: 'Cron', isMonospace: true },
    { key: 'format', header: 'Format' },
    { key: 'subjectLine', header: 'Email Subject' },
    { key: 'lastRunAt', header: 'Last Run', width: 16 },
    { key: 'nextRunAt', header: 'Next Run', width: 16 },
    { key: 'isActive', header: 'Active?' },
    { key: 'createdAt', header: 'Created', width: 16 },
    { key: 'createdById', header: 'Owner ID', isNum: true, width: 8 },
  ],
  export_audit: [
    { key: 'id', header: 'Audit ID', isNum: true, width: 8 },
    { key: 'reportUuid', header: 'Report UUID', isMonospace: true },
    { key: 'reportType', header: 'Type' },
    { key: 'reportName', header: 'Name' },
    { key: 'format', header: 'Format' },
    { key: 'status', header: 'Status' },
    { key: 'generatedById', header: 'Generator ID', isNum: true, width: 10 },
    { key: 'dateRangeStart', header: 'From', width: 14 },
    { key: 'dateRangeEnd', header: 'To', width: 14 },
    { key: 'rowCount', header: 'Rows', isNum: true },
    { key: 'fileSizeBytes', header: 'Bytes', isNum: true },
    { key: 'downloadUrl', header: 'Download URL' },
    { key: 'jobId', header: 'Job ID', isMonospace: true },
    { key: 'scheduledReportId', header: 'Scheduled Job', isNum: true, width: 12 },
    { key: 'createdAt', header: 'Created At', width: 16 },
    { key: 'expiresAt', header: 'Expires At', width: 16 },
    { key: 'errorMessage', header: 'Error' },
  ],
};

export default EXPORT_COLUMN_CATALOG;
